In [329]:
%config IPCompleter.greedy=True

In [1]:
ls

 El volumen de la unidad C es Windows
 El n£mero de serie del volumen es: 769A-754B

 Directorio de C:\Users\Emilio\Documents\GitHub\TP Org de datos\TP-Org-de-datos-

18/04/2020  00:34    <DIR>          .
18/04/2020  00:34    <DIR>          ..
16/04/2020  17:35                66 .gitattributes
18/04/2020  00:34    <DIR>          .ipynb_checkpoints
04/02/2020  17:38            89.958 Oscars-demographics-DFE.csv
16/04/2020  17:40        22.962.781 Pandas Cookbook -Theodore Petrou.pdf
16/04/2020  17:35                79 README.md
16/12/2019  20:36            22.746 sample_submission.csv
16/12/2019  20:36           420.783 test.csv
16/12/2019  20:36           987.712 train.csv
18/04/2020  00:34                72 Untitled.ipynb
               8 archivos     24.484.197 bytes
               3 dirs  342.779.379.712 bytes libres

# Video 1 Pandas: Analisis y estadisticas sobre los datos

In [81]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
%config IPCompleter.greedy=True

In [68]:
# Load the Data and take a quick look.
oscars_demographics = pd.read_csv('Oscars-demographics-DFE.csv', sep=",",encoding='latin-1')
oscars_demographics.tail()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
436,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,Rachel Weisz,NaN,NaN,NaN,NaN
437,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,Danny Boyle,NaN,NaN,NaN,NaN
438,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,Jason Robards,NaN,NaN,NaN,NaN
439,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,James Coburn,NaN,NaN,NaN,NaN
440,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,John Huston,NaN,NaN,NaN,NaN

In [11]:
oscars_short = pd.read_csv('Oscars-demographics-DFE.csv', encoding ='latin-1',\
                          usecols=['birthplace','date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award',\
                                  'award','movie','person'])
oscars_short.tail()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [13]:
# Information about the dataset #en R es dataframe
oscars_demographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 27 columns):
_unit_id                         441 non-null int64
_golden                          441 non-null bool
_unit_state                      441 non-null object
_trusted_judgments               441 non-null int64
_last_judgment_at                416 non-null object
birthplace                       441 non-null object
birthplace:confidence            441 non-null float64
date_of_birth                    441 non-null object
date_of_birth:confidence         441 non-null float64
race_ethnicity                   441 non-null object
race_ethnicity:confidence        441 non-null float64
religion                         441 non-null object
religion:confidence              441 non-null float64
sexual_orientation               441 non-null object
sexual_orientation:confidence    441 non-null float64
year_of_award                    441 non-null int64
year_of_award:confidence         441 non-null float64
award                            441 non-null object
biourl                           441 non-null object
birthplace_gold                  9 non-null object
date_of_birth_gold               8 non-null object
movie                            441 non-null object
person                           441 non-null object
race_ethnicity_gold              2 non-null object
religion_gold                    10 non-null object
sexual_orientation_gold          3 non-null object
year_of_award_gold               11 non-null float64
dtypes: bool(1), float64(7), int64(3), object(16)
memory usage: 90.1+ KB

In [14]:
# Some stats about the numeric columns in our dataset
oscars_demographics.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

In [19]:
# Estrucuturas del dataframe
oscars_index = oscars_demographics.index
oscars_columns = oscars_demographics.columns
oscars_data = oscars_demographics.values

In [17]:
oscars_index

RangeIndex(start=0, stop=441, step=1)

In [21]:
oscars_columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence', 'year_of_award',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'person', 'race_ethnicity_gold',
       'religion_gold', 'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [24]:
oscars_data

array([[670454353, False, 'finalized', ..., nan, nan, nan],
       [670454354, False, 'finalized', ..., nan, nan, nan],
       [670454355, False, 'finalized', ..., nan, nan, nan],
       ...,
       [670964912, False, 'finalized', ..., nan, nan, nan],
       [670964956, False, 'finalized', ..., nan, nan, nan],
       [670972898, False, 'finalized', ..., nan, nan, nan]], dtype=object)

In [25]:
type(oscars_index)

pandas.core.indexes.range.RangeIndex

In [27]:
type(oscars_columns)

pandas.core.indexes.base.Index

In [29]:
type(oscars_data)

numpy.ndarray

In [33]:
oscars_demographics.dtypes

_unit_id                           int64
_golden                             bool
_unit_state                       object
_trusted_judgments                 int64
_last_judgment_at                 object
birthplace                        object
birthplace:confidence            float64
date_of_birth                     object
date_of_birth:confidence         float64
race_ethnicity                    object
race_ethnicity:confidence        float64
religion                          object
religion:confidence              float64
sexual_orientation                object
sexual_orientation:confidence    float64
year_of_award                      int64
year_of_award:confidence         float64
award                             object
biourl                            object
birthplace_gold                   object
date_of_birth_gold                object
movie                             object
person                            object
race_ethnicity_gold               object
religion_gold                     object
sexual_orientation_gold           object
year_of_award_gold               float64
dtype: object

In [41]:
# Using dtypes we saw the data types of each column. To see the quantity of columns with each data type we can use value_counts()
oscars_demographics.dtypes.value_counts()

object     16
float64     7
int64       3
bool        1
dtype: int64

# Video 2 Pandas: Analisis y Estadisticas sobre los datos

In [38]:
# We can indicate a column nate, using index operator
oscars_demographics['person']

0           Lewis Milestone
1               Frank Lloyd
2           Lewis Milestone
3             Norman Taurog
4             Frank Borzage
5               Frank Lloyd
6               Frank Capra
7                 John Ford
8               Frank Capra
9               Leo McCarey
10              Frank Capra
11           Victor Fleming
12                John Ford
13                John Ford
14            William Wyler
15           Michael Curtiz
16              Leo McCarey
17           Jerome Robbins
18             Billy Wilder
19            William Wyler
20               Elia Kazan
21              John Huston
22     Joseph L. Mankiewicz
23     Joseph L. Mankiewicz
24           George Stevens
25                John Ford
26           Fred Zinnemann
27               Elia Kazan
28             Delbert Mann
29           George Stevens
               ...
411                Mo'Nique
412             Melissa Leo
413         Octavia Spencer
414           Anne Hathaway
415          Lupita Nyong'o
416            Billy Wilder
417           Ginger Rogers
418               Tom Hanks
419          Michael Cimino
420              Mary Astor
421          Angelina Jolie
422               Lee Grant
423             Anne Revere
424            Faye Dunaway
425              Van Heflin
426         Joanne Woodward
427             Gary Cooper
428        Elizabeth Taylor
429            Hilary Swank
430            Hilary Swank
431         Gwyneth Paltrow
432          Jack Albertson
433                Mo'Nique
434       Marcia Gay Harden
435            Maggie Smith
436            Rachel Weisz
437             Danny Boyle
438           Jason Robards
439            James Coburn
440             John Huston
Name: person, Length: 441, dtype: object

In [44]:
# We can also use the dot notation to indicate which column to select
oscars_demographics.person

0           Lewis Milestone
1               Frank Lloyd
2           Lewis Milestone
3             Norman Taurog
4             Frank Borzage
5               Frank Lloyd
6               Frank Capra
7                 John Ford
8               Frank Capra
9               Leo McCarey
10              Frank Capra
11           Victor Fleming
12                John Ford
13                John Ford
14            William Wyler
15           Michael Curtiz
16              Leo McCarey
17           Jerome Robbins
18             Billy Wilder
19            William Wyler
20               Elia Kazan
21              John Huston
22     Joseph L. Mankiewicz
23     Joseph L. Mankiewicz
24           George Stevens
25                John Ford
26           Fred Zinnemann
27               Elia Kazan
28             Delbert Mann
29           George Stevens
               ...
411                Mo'Nique
412             Melissa Leo
413         Octavia Spencer
414           Anne Hathaway
415          Lupita Nyong'o
416            Billy Wilder
417           Ginger Rogers
418               Tom Hanks
419          Michael Cimino
420              Mary Astor
421          Angelina Jolie
422               Lee Grant
423             Anne Revere
424            Faye Dunaway
425              Van Heflin
426         Joanne Woodward
427             Gary Cooper
428        Elizabeth Taylor
429            Hilary Swank
430            Hilary Swank
431         Gwyneth Paltrow
432          Jack Albertson
433                Mo'Nique
434       Marcia Gay Harden
435            Maggie Smith
436            Rachel Weisz
437             Danny Boyle
438           Jason Robards
439            James Coburn
440             John Huston
Name: person, Length: 441, dtype: object

In [51]:
# To verify the data type os the output
type(oscars_demographics['person'])

pandas.core.series.Series

In [52]:
oscars_demographics['person'].info()

AttributeError: 'Series' object has no attribute 'info'

In [48]:
type(oscars_demographics['person'].to_frame())

pandas.core.frame.DataFrame

In [67]:
oscars_demographics['person'].to_frame().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 1 columns):
person    441 non-null object
dtypes: object(1)
memory usage: 3.5+ KB

In [54]:
# metodos que se pueden hacer sobre dataframe y otros sobre series
# attr_methods

In [58]:
s_attr_methods = set(dir(pd.Series))
len(s_attr_methods)

464

In [59]:
s_attr_methods

{'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_expand_axes',
 '_find_valid_index',
 '_formatting_values',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'as_blocks',
 'as_matrix',
 'asfreq',
 'asobject',
 'asof',
 'astype',
 'at',
 'at_time',
 'autocorr',
 'axes',
 'base',
 'between',
 'between_time',
 'bfill',
 'blocks',
 'bool',
 'cat',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compound',
 'compress',
 'consolidate',
 'convert_objects',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'data',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dt',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_array',
 'from_csv',
 'ftype',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_value',
 'get_values',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imag',
 'index',
 'infer_objects',
 'interpolate',
 'is_copy',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'itemsize',
 'iteritems',
 'ix',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'nonzero',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'ptp',
 'put',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'real',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'select',
 'sem',
 'set_axis',
 'set_value',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sortlevel',
 'squeeze',
 'std',
 'str',
 'strides',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_period',
 'to_pickle',
 'to_sparse',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'tolist',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'valid',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs'}

In [72]:
# Selecting two columns with different data types:
oscars_movie = oscars_demographics['movie']
# averiguar el tipo de dato que tiene la columna 'movie'
type(oscars_movie)

pandas.core.series.Series

In [163]:
oscars_years = oscars_demographics['year_of_award']
# averiguar el tipo de dato que tiene la columan 'year award'
type(oscars_years)

pandas.core.series.Series

In [75]:
oscars_movie.head() # es iuna serie que tiene las peliculas

0               Two Arabian Knights
1                   The Divine Lady
2    All Quiet on the Western Front
3                            Skippy
4                          Bad Girl
Name: movie, dtype: object

In [77]:
oscars_years.head() # es una serie que tiene los años de las peliculas

0    1927
1    1930
2    1931
3    1932
4    1933
Name: year_of_award, dtype: int64

In [80]:
# Vemos el volumen relativo (nivel de ocurrencia o participacion de ocurrencia sobre el total)
oscars_years.value_counts() # nos muestra como es la distribucion

1969    8
2005    7
1961    7
1999    7
2009    7
1976    7
1977    6
1953    6
1967    6
1990    6
1942    6
1940    6
1941    6
1938    6
1979    6
1958    6
1980    6
1994    6
1949    6
1997    6
2000    6
2001    6
1973    6
2003    6
2006    6
2007    6
1946    6
1970    6
1963    5
1964    5
       ..
1995    5
1993    5
1992    5
1991    5
1989    5
1988    5
1986    5
1985    5
1939    5
1983    5
1982    5
1981    5
1975    5
1972    5
1937    4
2014    4
1971    4
1974    4
1984    4
1987    4
1998    4
2004    4
1936    3
1935    3
1934    3
1932    3
1931    3
1929    2
1933    1
1927    1
Name: year_of_award, Length: 87, dtype: int64

In [82]:
# al igual que antes, se puede hacer lo mismo para 'year_of_award' y ver su porcentual
oscars_demographics['year_of_award'].value_counts()

1969    8
2005    7
1961    7
1999    7
2009    7
1976    7
1977    6
1953    6
1967    6
1990    6
1942    6
1940    6
1941    6
1938    6
1979    6
1958    6
1980    6
1994    6
1949    6
1997    6
2000    6
2001    6
1973    6
2003    6
2006    6
2007    6
1946    6
1970    6
1963    5
1964    5
       ..
1995    5
1993    5
1992    5
1991    5
1989    5
1988    5
1986    5
1985    5
1939    5
1983    5
1982    5
1981    5
1975    5
1972    5
1937    4
2014    4
1971    4
1974    4
1984    4
1987    4
1998    4
2004    4
1936    3
1935    3
1934    3
1932    3
1931    3
1929    2
1933    1
1927    1
Name: year_of_award, Length: 87, dtype: int64

###### Value_counts() returns a series, where the value is the index, and the count associated to the value is the element.

###### Counting the unmber of elements in a serie: size, shape, len() → para calcular a mano las estadisticas que se puede informar con describe()

In [83]:
oscars_demographics.size

11907

In [85]:
oscars_demographics.shape

(441, 27)

In [87]:
len(oscars_demographics)

441

In [88]:
oscars_demographics.count()

_unit_id                         441
_golden                          441
_unit_state                      441
_trusted_judgments               441
_last_judgment_at                416
birthplace                       441
birthplace:confidence            441
date_of_birth                    441
date_of_birth:confidence         441
race_ethnicity                   441
race_ethnicity:confidence        441
religion                         441
religion:confidence              441
sexual_orientation               441
sexual_orientation:confidence    441
year_of_award                    441
year_of_award:confidence         441
award                            441
biourl                           441
birthplace_gold                    9
date_of_birth_gold                 8
movie                            441
person                           441
race_ethnicity_gold                2
religion_gold                     10
sexual_orientation_gold            3
year_of_award_gold                11
dtype: int64

In [89]:
# Diferencia entre size, shape, len() y count()

In [91]:
# Aunque size (shape y len) nos van a informar el total de nro de elementos (incluyendo nulls)
oscars_demographics['date_of_birth_gold'].size

441

In [93]:
# count() informara el nro de elementos con valores distintos de null
oscars_demographics['date_of_birth_gold'].count()

8

In [95]:
# Debido a este resultado, sabemos que hay valores null. Para confirmar estos debemos correr isnull() el cual retornara una serie de elementos
oscars_demographics['date_of_birth_gold'].isnull()
# si tiene valor asociado null indica True. En caso que no, devuelve True

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21     False
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...
411    False
412     True
413     True
414     True
415     True
416     True
417     True
418     True
419     True
420     True
421     True
422     True
423     True
424     True
425     True
426     True
427     True
428     True
429     True
430     True
431     True
432     True
433     True
434     True
435     True
436     True
437     True
438     True
439     True
440     True
Name: date_of_birth_gold, Length: 441, dtype: bool

In [98]:
# se puede chequear si hay valores null usando hasnans (tienen Nan)
oscars_demographics['date_of_birth_gold'].hasnans
# si devuelve True significa que hay valores Nans en la serie/columna

True

In [101]:
# Necesitamos tomar una decision sobre que hacer con los valores null. A veces podemos ignorarlos, otra veces podemos eliminarlos
oscars_demographics.count()

_unit_id                         441
_golden                          441
_unit_state                      441
_trusted_judgments               441
_last_judgment_at                416
birthplace                       441
birthplace:confidence            441
date_of_birth                    441
date_of_birth:confidence         441
race_ethnicity                   441
race_ethnicity:confidence        441
religion                         441
religion:confidence              441
sexual_orientation               441
sexual_orientation:confidence    441
year_of_award                    441
year_of_award:confidence         441
award                            441
biourl                           441
birthplace_gold                    9
date_of_birth_gold                 8
movie                            441
person                           441
race_ethnicity_gold                2
religion_gold                     10
sexual_orientation_gold            3
year_of_award_gold                11
dtype: int64

In [103]:
oscars_demographics['date_of_birth_gold']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21      5-Aug-06
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29           NaN
         ...
411    11-Dec-67
412          NaN
413          NaN
414          NaN
415          NaN
416          NaN
417          NaN
418          NaN
419          NaN
420          NaN
421          NaN
422          NaN
423          NaN
424          NaN
425          NaN
426          NaN
427          NaN
428          NaN
429          NaN
430          NaN
431          NaN
432          NaN
433          NaN
434          NaN
435          NaN
436          NaN
437          NaN
438          NaN
439          NaN
440          NaN
Name: date_of_birth_gold, Length: 441, dtype: object

In [105]:
#cargo en una variable la serien 'date_of_birth_gold
oscars_date_of_birth_gold = oscars_demographics['date_of_birth_gold']

In [107]:
# Completo Nan con valores especificos con el atributo .fillna()
oscars_date_of_birth_gold_fillna = oscars_date_of_birth_gold.fillna('None')

In [110]:
# ahora en lugar de contar 8 valores null, va a contar los strings 'None' que pase com parametro a fillna
oscars_date_of_birth_gold_fillna.count()

441

In [112]:
oscars_date_of_birth_gold_fillna.size

441

In [114]:
# Elimino elementos Nan 
oscars_date_of_birth_gold_dropped = oscars_date_of_birth_gold.dropna()

In [116]:
#Tanto el count como el size nos volveran a psar los datos que tenian los datos inicialmente definidos porque dropeamos Nan
oscars_date_of_birth_gold_dropped.count()

8

## Estadisticas basicas: min, max, median, std, sum y metodos describe()

In [125]:
oscars_demographics._trusted_judgments.min(),oscars_demographics._trusted_judgments.max(),oscars_demographics._trusted_judgments.median(),oscars_demographics._trusted_judgments.std(),oscars_demographics._trusted_judgments.sum()

(3, 95, 3.0, 19.015540899806783, 3368)

In [126]:
oscars_demographics._trusted_judgments.describe()

count    441.000000
mean       7.637188
std       19.015541
min        3.000000
25%        3.000000
50%        3.000000
75%        3.000000
max       95.000000
Name: _trusted_judgments, dtype: float64

In [129]:
# Si quiero hacer lo mismo sobre una columna que sea object, los valores no van a ser lo mismo porque no pueden hacer estadisticas sobre strings
oscars_demographics.movie.describe()

count                     441
unique                    336
top       Million Dollar Baby
freq                        5
Name: movie, dtype: object

In [130]:
# Si quiero correr un describe() sobre todo el dataframe, me va a indicar las estadisticas de aquellas columnas que sean numericias
oscars_demographics.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

# Video 3 Pandas: Analisis y Estadisticas sobre los datos

### Operaciones sobre series

In [132]:
oscars_demographics['_trusted_judgments']

0       3
1       3
2       3
3       3
4       3
5       3
6       3
7       3
8       3
9       3
10      3
11      3
12      3
13      3
14      3
15      3
16      3
17      3
18      3
19      3
20      3
21     82
22      3
23      3
24      3
25      3
26      3
27      3
28      3
29      3
       ..
411    86
412     3
413     3
414     3
415     3
416     3
417     3
418     3
419     3
420     3
421     3
422     3
423     3
424     3
425     3
426     3
427     3
428     3
429     3
430    86
431     3
432     3
433     3
434     3
435     3
436     3
437     3
438     3
439     3
440     3
Name: _trusted_judgments, Length: 441, dtype: int64

In [133]:
oscars_demographics['_trusted_judgments'].mean()

7.63718820861678

In [134]:
oscars_demographics['_trusted_judgments'].min()

3

In [135]:
oscars_demographics['_trusted_judgments'].max()

95

In [141]:
# Podemos contar las ocurrencias de los elementos de la serie '_trusted_judgments'
# para el elementos 3, vemos que se contaron 416 valores
oscars_demographics['_trusted_judgments'].value_counts()

3     416
91      5
87      3
86      3
84      2
76      2
75      2
95      1
92      1
90      1
89      1
85      1
82      1
81      1
62      1
Name: _trusted_judgments, dtype: int64

In [152]:
oscars_demographics['_trusted_judgments'].min()+1

4

In [153]:
oscars_demographics['_trusted_judgments']

0       3
1       3
2       3
3       3
4       3
5       3
6       3
7       3
8       3
9       3
10      3
11      3
12      3
13      3
14      3
15      3
16      3
17      3
18      3
19      3
20      3
21     82
22      3
23      3
24      3
25      3
26      3
27      3
28      3
29      3
       ..
411    86
412     3
413     3
414     3
415     3
416     3
417     3
418     3
419     3
420     3
421     3
422     3
423     3
424     3
425     3
426     3
427     3
428     3
429     3
430    86
431     3
432     3
433     3
434     3
435     3
436     3
437     3
438     3
439     3
440     3
Name: _trusted_judgments, Length: 441, dtype: int64

In [154]:
#le sumo una ocurrencia a los elementos '_trusted_judgments'
mas_uno=oscars_demographics['_trusted_judgments']+1

In [150]:
mas_uno.min()

4

In [151]:
mas_uno

0       4
1       4
2       4
3       4
4       4
5       4
6       4
7       4
8       4
9       4
10      4
11      4
12      4
13      4
14      4
15      4
16      4
17      4
18      4
19      4
20      4
21     83
22      4
23      4
24      4
25      4
26      4
27      4
28      4
29      4
       ..
411    87
412     4
413     4
414     4
415     4
416     4
417     4
418     4
419     4
420     4
421     4
422     4
423     4
424     4
425     4
426     4
427     4
428     4
429     4
430    87
431     4
432     4
433     4
434     4
435     4
436     4
437     4
438     4
439     4
440     4
Name: _trusted_judgments, Length: 441, dtype: int64

In [155]:
mas_uno.head()

0    4
1    4
2    4
3    4
4    4
Name: _trusted_judgments, dtype: int64

In [156]:
mas_uno.min()

4

In [157]:
mas_uno.max()

96

In [159]:
mas_uno.value_counts()

4     416
92      5
88      3
87      3
85      2
77      2
76      2
96      1
93      1
91      1
90      1
86      1
83      1
82      1
63      1
Name: _trusted_judgments, dtype: int64

In [161]:
oscars_demographics['_trusted_judgments']*3

0        9
1        9
2        9
3        9
4        9
5        9
6        9
7        9
8        9
9        9
10       9
11       9
12       9
13       9
14       9
15       9
16       9
17       9
18       9
19       9
20       9
21     246
22       9
23       9
24       9
25       9
26       9
27       9
28       9
29       9
      ...
411    258
412      9
413      9
414      9
415      9
416      9
417      9
418      9
419      9
420      9
421      9
422      9
423      9
424      9
425      9
426      9
427      9
428      9
429      9
430    258
431      9
432      9
433      9
434      9
435      9
436      9
437      9
438      9
439      9
440      9
Name: _trusted_judgments, Length: 441, dtype: int64

si multiplicamos una serie, retornara otra serie con la operacion aplicada a cada uno de los elementos. Tambien podemos usar otros operadores como sum(+), minus(-), division(//), y potencia(* *).\
Notar que los oepradores de division consecutiva(//) es utilizado para division entera y el signigo de porcentaje (%) para los modeulos operadores los cuales retornan el recordatorio despues de la division

tambien poemos usar la comparacion de operadores, como **greater than** (>), **less thant**(<) o **greater than or equal to**(>=), **equal to**(==) y  **not equal to** (!=). Estos tambien retornan una serie, donde cada elemento es True o FALSE basado en el resultado de la comparacion.

In [165]:
#comparamos cuantos años '1969' son iguales para las ocurrencias de valor de esa serie para ese año (van a tener valor True)
#comparan una serie con un valor
(oscars_years==1969).value_counts()

False    433
True       8
Name: year_of_award, dtype: int64

Para cada operador, hay tambien un metodo que hace lo mismo

**Aritmeticos**

En lugar de +,-,/,//,%, podemos usar: add, sub, mul, div, floordiv, mod, pow

**Comparacion**

En lugar de <,>,<=,>=,==,!=, podemos usar: it, gt, le, ge, eq, ne

In [167]:
oscars_years.eq(1969).value_counts()

False    433
True       8
Name: year_of_award, dtype: int64

### Los metodos pueden encadenarse

Podemos usar el punto (.) para concatenar metodos
Podemos usar barra invertida (back slash) para continuar la secuencia en la siguiente linea
Para facilitar la lectura podemos usar un metodo por linea
Podemos tambien usar parentesis para indicar la sentence completa

In [ ]:
# Digamos que queremos contar los valores NaN sobre la serie 'Year_of_award_gold', para eso podemos usar isnull() y sum()

In [168]:
oscars_demographics['year_of_award_gold'].isnull().sum()

430

In [172]:
oscars_demographics['year_of_award_gold'].sum().isnull()

AttributeError: 'numpy.float64' object has no attribute 'isnull'

In [174]:
# Se puede calcular el promedio de valores NaN con mean()
oscars_demographics['year_of_award_gold'].isnull().mean()

0.9750566893424036

Para hacer un split en dos lineas podemos usar \

In [175]:
oscars_demographics['year_of_award_gold'].isnull()\ 
.mean()

0.9750566893424036

**o podemos escribirlo entre parentesis ()**

In [177]:
(oscars_demographics['year_of_award_gold']
 .isnull()
 .mean())

0.9750566893424036

# Video 4 Pandas: Limpieza de dataset y manejo de indices

## Cleaning el Dataset

En esta seccion vamos a limpiar los datos y dejarlos listos para todo el analisis. Los pasos que vamos a hacer son:

* Mantener las columnas que estamos interesados usar
* Limpiar los valores Null del dataset, solo eliminando el registro completo(la pelicula) si tiene null en la columna
* Converir año a INT (from float)

In [203]:
# Mantener solo las columnas que nos interesan
oscars = oscars_demographics[['birthplace',
                             'date_of_birth','race_ethnicity','religion',
                            'sexual_orientation','year_of_award','award','movie','person']]

In [204]:
oscars.to_excel("dataset oscars sin limpiar.xlsx")

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [187]:
# Limpiamos Nas
print(len(oscars))

441

In [246]:
# Consulta: Limpie Nas pero me sigue indicando el mismo nro de filas a excepcion del ejercicio del video

In [192]:
# antes de ejecutar dropna, me fijo si tiene valores null y los cuento
oscars.isnull.value_counts()

AttributeError: 'function' object has no attribute 'value_counts'

In [206]:
oscars.dropna(inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
oscars.to_excel("dataset oscars sin limpiar.xlsx")

In [191]:
print(len(oscars))

441

In [198]:
oscars.dropna(inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [199]:
print(len(oscars))

441

In [211]:
oscars.isnull().sum()

birthplace            0
date_of_birth         0
race_ethnicity        0
religion              0
sexual_orientation    0
year_of_award         0
award                 0
movie                 0
person                0
dtype: int64

In [201]:
type(oscars)

pandas.core.frame.DataFrame

In [202]:
print(oscars)

                              birthplace date_of_birth race_ethnicity  \
0                      Chisinau, Moldova   30-Sep-1895          White
1                      Glasgow, Scotland    2-Feb-1886          White
2                      Chisinau, Moldova   30-Sep-1895          White
3                            Chicago, Il   23-Feb-1899          White
4                     Salt Lake City, Ut   23-Apr-1894          White
5                      Glasgow, Scotland    2-Feb-1886          White
6              Bisacquino, Sicily, Italy   18-May-1897          White
7                     Cape Elizabeth, Me    1-Feb-1894          White
8              Bisacquino, Sicily, Italy   18-May-1897          White
9                        Los Angeles, Ca    3-Oct-1898          White
10             Bisacquino, Sicily, Italy   18-May-1897          White
11                          Pasadena, Ca   23-Feb-1883          White
12                    Cape Elizabeth, Me    1-Feb-1894          White
13                    Cape Elizabeth, Me    1-Feb-1894          White
14   Mulhouse, Haut-Rhin, Alsace, France    1-Jul-1902          White
15                     Budapest, Hungary   24-Dec-1886          White
16                       Los Angeles, Ca    3-Oct-1898          White
17                         New York City     11-Oct-18          White
18               Sucha, Galicia, Austria     22-Jun-06          White
19   Mulhouse, Haut-Rhin, Alsace, France    1-Jul-1902          White
20                      Istanbul, Turkey      7-Sep-09          White
21                            Nevada, Mo      5-Aug-06          White
22                      Wilkes-Barre, Pa     11-Feb-09          White
23                      Wilkes-Barre, Pa     11-Feb-09          White
24                           Oakland, Ca     18-Dec-04          White
25                    Cape Elizabeth, Me    1-Feb-1894          White
26                       Vienna, Austria     29-Apr-07          White
27                      Istanbul, Turkey      7-Sep-09          White
28                          Lawrence, Ks     30-Jan-20          White
29                           Oakland, Ca     18-Dec-04          White
..                                   ...           ...            ...
411                         Woodlawn, Md     11-Dec-67          Black
412                        New York City     14-Sep-60          White
413                       Montgomery, Al     25-May-72          Black
414                         Brooklyn, Ny     12-Nov-82          White
415                  Mexico City, Mexico      1-Mar-83          Black
416              Sucha, Galicia, Austria     22-Jun-06          White
417                     Independence, Mo     16-Jul-11          White
418                          Concord, Ca      9-Jul-56          White
419                        New York City      3-Feb-39          White
420                           Quincy, Il      3-May-06          White
421                      Los Angeles, Ca      4-Jun-75          White
422                        New York City     31-Oct-27          White
423                        New York City   25-Jun-1903          White
424                           Bascom, Fl     14-Jan-41          White
425                          Walters, Ok     13-Dec-10          White
426                      Thomasville, Ga     27-Feb-30          White
427                           Helena, Mt    7-May-1901          White
428                      London, England     27-Feb-32          White
429                          Lincoln, Ne     30-Jul-74          White
430                          Lincoln, Ne     30-Jul-74          White
431                      Los Angeles, Ca     27-Sep-72          White
432                           Malden, Ma     16-Jun-07          White
433                         Woodlawn, Md     11-Dec-67          Black
434                         La Jolla, Ca     14-Aug-59          White
435               Ilford, Essex, England     28-Dec-34          White
436                      London, England      7-Mar-71          White
437                  Manchester, England     20-Oct-56          White
438                          Chicago, Il     26-Jul-22          White
439                           Laurel, Ne     31-Aug-28          White
440                           Nevada, Mo      5-Aug-06          White

                 religion sexual_orientation  year_of_award  \
0                      Na           Straight           1927
1                      Na           Straight           1930
2                      Na           Straight           1931
3                      Na           Straight           1932
4          Roman Catholic           Straight           1933
5                      Na           Straight           1934
6          Roman Catholic           Straight           1935
7          Roman Catholic           Bisexual           1936
8          Roman Catholic           Straight           1937
9                      Na           Straight           1938
10         Roman Catholic           Straight           1939
11                     Na           Straight           1940
12         Roman Catholic           Bisexual           1941
13         Roman Catholic           Bisexual           1942
14                     Na           Straight           1943
15                     Na           Straight           1944
16                     Na           Straight           1945
17                 Jewish                Gay           1962
18                 Jewish           Straight           1946
19                     Na           Straight           1947
20                     Na           Straight           1948
21                     Na           Straight           1949
22                 Jewish           Straight           1950
23                 Jewish           Straight           1951
24                     Na           Straight           1952
25         Roman Catholic           Bisexual           1953
26                 Jewish           Straight           1954
27                     Na           Straight           1955
28           Presbyterian           Straight           1956
29                     Na           Straight           1957
..                    ...                ...            ...
411                    Na           Straight           2010
412                    Na           Straight           2011
413                    Na                 Na           2012
414             Christian           Straight           2013
415                    Na                 Na           2014
416                Jewish           Straight           1961
417     Christian Science           Straight           1941
418  Born-Again Christian           Straight           1994
419                    Na           Straight           1979
420        Roman Catholic           Straight           1942
421              Buddhist           Bisexual           2000
422                Jewish           Straight           1976
423                    Na           Straight           1946
424        Roman Catholic           Straight           1977
425                    Na           Straight           1943
426                    Na           Straight           1958
427        Roman Catholic           Straight           1953
428                Jewish           Straight           1967
429                    Na           Straight           2005
430                    Na           Straight           2005
431                Jewish           Straight           1999
432                    Na                 Na           1969
433                    Na           Straight           2010
434                    Na           Straight           2001
435                    Na           Straight           1970
436                Jewish           Straight           2006
437        Roman Catholic           Straight           2009
438                    Na           Straight           1977
439                    Na           Straight           1999
440                    Na           Straight           1949

                       award                             movie  \
0              Best Director               Two Arabian Knights
1              Best Director                   The Divine Lady
2              Best Director    All Quiet on the Western Front
3              Best Director                            Skippy
4              Best Director                          Bad Girl
5              Best Director                         Cavalcade
6              Best Director             It Happened One Night
7              Best Director                      The Informer
8              Best Director            Mr. Deeds Goes to Town
9              Best Director                   The Awful Truth
10             Best Director        You Can't Take It with You
11             Best Director                Gone with the Wind
12             Best Director               The Grapes of Wrath
13             Best Director           How Green Was My Valley
14             Best Director                      Mrs. Miniver
15             Best Director                        Casablanca
16             Best Director                      Going My Way
17             Best Director                   West Side Story
18             Best Director                  The Lost Weekend
19             Best Director       The Best Years of Our Lives
20             Best Director             Gentleman's Agreement
21             Best Director  The Treasure of the Sierra Madre
22             Best Director           A Letter to Three Wives
23             Best Director                     All About Eve
24             Best Director                A Place in the Sun
25             Best Director                     The Quiet Man
26             Best Director             From Here to Eternity
27             Best Director                 On the Waterfront
28             Best Director                             Marty
29             Best Director                             Giant
..                       ...                               ...
411  Best Supporting Actress                          Precious
412  Best Supporting Actress                       The Fighter
413  Best Supporting Actress                          The Help
414  Best Supporting Actress                   Les MisÌ©rables
415  Best Supporting Actress                  12 Years a Slave
416            Best Director                     The Apartment
417             Best Actress                       Kitty Foyle
418               Best Actor                      Philadelphia
419            Best Director                   The Deer Hunter
420  Best Supporting Actress                     The Great Lie
421  Best Supporting Actress                 Girl, Interrupted
422  Best Supporting Actress                           Shampoo
423  Best Supporting Actress                   National Velvet
424             Best Actress                           Network
425    Best Supporting Actor                      Johnny Eager
426             Best Actress            The Three Faces of Eve
427               Best Actor                         High Noon
428             Best Actress   Who's Afraid of Virginia Woolf?
429             Best Actress               Million Dollar Baby
430             Best Actress               Million Dollar Baby
431             Best Actress               Shakespeare in Love
432    Best Supporting Actor             The Subject Was Roses
433  Best Supporting Actress                          Precious
434  Best Supporting Actress                           Pollock
435             Best Actress     The Prime of Miss Jean Brodie
436  Best Supporting Actress             The Constant Gardener
437            Best Director               Slumdog Millionaire
438    Best Supporting Actor           All the President's Men
439    Best Supporting Actor                        Affliction
440            Best Director  The Treasure of the Sierra Madre

                   person
0         Lewis Milestone
1             Frank Lloyd
2         Lewis Milestone
3           Norman Taurog
4           Frank Borzage
5             Frank Lloyd
6             Frank Capra
7               John Ford
8             Frank Capra
9             Leo McCarey
10            Frank Capra
11         Victor Fleming
12              John Ford
13              John Ford
14          William Wyler
15         Michael Curtiz
16            Leo McCarey
17         Jerome Robbins
18           Billy Wilder
19          William Wyler
20             Elia Kazan
21            John Huston
22   Joseph L. Mankiewicz
23   Joseph L. Mankiewicz
24         George Stevens
25              John Ford
26         Fred Zinnemann
27             Elia Kazan
28           Delbert Mann
29         George Stevens
..                    ...
411              Mo'Nique
412           Melissa Leo
413       Octavia Spencer
414         Anne Hathaway
415        Lupita Nyong'o
416          Billy Wilder
417         Ginger Rogers
418             Tom Hanks
419        Michael Cimino
420            Mary Astor
421        Angelina Jolie
422             Lee Grant
423           Anne Revere
424          Faye Dunaway
425            Van Heflin
426       Joanne Woodward
427           Gary Cooper
428      Elizabeth Taylor
429          Hilary Swank
430          Hilary Swank
431       Gwyneth Paltrow
432        Jack Albertson
433              Mo'Nique
434     Marcia Gay Harden
435          Maggie Smith
436          Rachel Weisz
437           Danny Boyle
438         Jason Robards
439          James Coburn
440           John Huston

[441 rows x 9 columns]

In [207]:
oscars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 441 entries, 0 to 440
Data columns (total 9 columns):
birthplace            441 non-null object
date_of_birth         441 non-null object
race_ethnicity        441 non-null object
religion              441 non-null object
sexual_orientation    441 non-null object
year_of_award         441 non-null int64
award                 441 non-null object
movie                 441 non-null object
person                441 non-null object
dtypes: int64(1), object(8)
memory usage: 34.5+ KB

In [210]:
# Veo que no haya valores nulos. Para lo cual si no hay, me indicaria el valor False. Si lo hubiera, True
oscars.isnull()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
411,False,False,False,False,False,False,False,False,False
412,False,False,False,False,False,False,False,False,False
413,False,False,False,False,False,False,False,False,False
414,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False
416,False,False,False,False,False,False,False,False,False
417,False,False,False,False,False,False,False,False,False
418,False,False,False,False,False,False,False,False,False
419,False,False,False,False,False,False,False,False,False
420,False,False,False,False,False,False,False,False,False
421,False,False,False,False,False,False,False,False,False
422,False,False,False,False,False,False,False,False,False
423,False,False,False,False,False,False,False,False,False
424,False,False,False,False,False,False,False,False,False
425,False,False,False,False,False,False,False,False,False
426,False,False,False,False,False,False,False,False,False
427,False,False,False,False,False,False,False,False,False
428,False,False,False,False,False,False,False,False,False
429,False,False,False,False,False,False,False,False,False
430,False,False,False,False,False,False,False,False,False
431,False,False,False,False,False,False,False,False,False
432,False,False,False,False,False,False,False,False,False
433,False,False,False,False,False,False,False,False,False
434,False,False,False,False,False,False,False,False,False
435,False,False,False,False,False,False,False,False,False
436,False,False,False,False,False,False,False,False,False
437,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False

## Indices (indexes)

* Los indices proveen de una etiqueta por cada fila
* Si no existe el indice explicitamente provisto, un RangeIndex se crea con labels comenzando en cero (0)

In [212]:
# el dataframe 'oscars' tiene un index Rangeindex
print(oscars)

                              birthplace date_of_birth race_ethnicity  \
0                      Chisinau, Moldova   30-Sep-1895          White
1                      Glasgow, Scotland    2-Feb-1886          White
2                      Chisinau, Moldova   30-Sep-1895          White
3                            Chicago, Il   23-Feb-1899          White
4                     Salt Lake City, Ut   23-Apr-1894          White
5                      Glasgow, Scotland    2-Feb-1886          White
6              Bisacquino, Sicily, Italy   18-May-1897          White
7                     Cape Elizabeth, Me    1-Feb-1894          White
8              Bisacquino, Sicily, Italy   18-May-1897          White
9                        Los Angeles, Ca    3-Oct-1898          White
10             Bisacquino, Sicily, Italy   18-May-1897          White
11                          Pasadena, Ca   23-Feb-1883          White
12                    Cape Elizabeth, Me    1-Feb-1894          White
13                    Cape Elizabeth, Me    1-Feb-1894          White
14   Mulhouse, Haut-Rhin, Alsace, France    1-Jul-1902          White
15                     Budapest, Hungary   24-Dec-1886          White
16                       Los Angeles, Ca    3-Oct-1898          White
17                         New York City     11-Oct-18          White
18               Sucha, Galicia, Austria     22-Jun-06          White
19   Mulhouse, Haut-Rhin, Alsace, France    1-Jul-1902          White
20                      Istanbul, Turkey      7-Sep-09          White
21                            Nevada, Mo      5-Aug-06          White
22                      Wilkes-Barre, Pa     11-Feb-09          White
23                      Wilkes-Barre, Pa     11-Feb-09          White
24                           Oakland, Ca     18-Dec-04          White
25                    Cape Elizabeth, Me    1-Feb-1894          White
26                       Vienna, Austria     29-Apr-07          White
27                      Istanbul, Turkey      7-Sep-09          White
28                          Lawrence, Ks     30-Jan-20          White
29                           Oakland, Ca     18-Dec-04          White
..                                   ...           ...            ...
411                         Woodlawn, Md     11-Dec-67          Black
412                        New York City     14-Sep-60          White
413                       Montgomery, Al     25-May-72          Black
414                         Brooklyn, Ny     12-Nov-82          White
415                  Mexico City, Mexico      1-Mar-83          Black
416              Sucha, Galicia, Austria     22-Jun-06          White
417                     Independence, Mo     16-Jul-11          White
418                          Concord, Ca      9-Jul-56          White
419                        New York City      3-Feb-39          White
420                           Quincy, Il      3-May-06          White
421                      Los Angeles, Ca      4-Jun-75          White
422                        New York City     31-Oct-27          White
423                        New York City   25-Jun-1903          White
424                           Bascom, Fl     14-Jan-41          White
425                          Walters, Ok     13-Dec-10          White
426                      Thomasville, Ga     27-Feb-30          White
427                           Helena, Mt    7-May-1901          White
428                      London, England     27-Feb-32          White
429                          Lincoln, Ne     30-Jul-74          White
430                          Lincoln, Ne     30-Jul-74          White
431                      Los Angeles, Ca     27-Sep-72          White
432                           Malden, Ma     16-Jun-07          White
433                         Woodlawn, Md     11-Dec-67          Black
434                         La Jolla, Ca     14-Aug-59          White
435               Ilford, Essex, England     28-Dec-34          White
436                      London, England      7-Mar-71          White
437                  Manchester, England     20-Oct-56          White
438                          Chicago, Il     26-Jul-22          White
439                           Laurel, Ne     31-Aug-28          White
440                           Nevada, Mo      5-Aug-06          White

                 religion sexual_orientation  year_of_award  \
0                      Na           Straight           1927
1                      Na           Straight           1930
2                      Na           Straight           1931
3                      Na           Straight           1932
4          Roman Catholic           Straight           1933
5                      Na           Straight           1934
6          Roman Catholic           Straight           1935
7          Roman Catholic           Bisexual           1936
8          Roman Catholic           Straight           1937
9                      Na           Straight           1938
10         Roman Catholic           Straight           1939
11                     Na           Straight           1940
12         Roman Catholic           Bisexual           1941
13         Roman Catholic           Bisexual           1942
14                     Na           Straight           1943
15                     Na           Straight           1944
16                     Na           Straight           1945
17                 Jewish                Gay           1962
18                 Jewish           Straight           1946
19                     Na           Straight           1947
20                     Na           Straight           1948
21                     Na           Straight           1949
22                 Jewish           Straight           1950
23                 Jewish           Straight           1951
24                     Na           Straight           1952
25         Roman Catholic           Bisexual           1953
26                 Jewish           Straight           1954
27                     Na           Straight           1955
28           Presbyterian           Straight           1956
29                     Na           Straight           1957
..                    ...                ...            ...
411                    Na           Straight           2010
412                    Na           Straight           2011
413                    Na                 Na           2012
414             Christian           Straight           2013
415                    Na                 Na           2014
416                Jewish           Straight           1961
417     Christian Science           Straight           1941
418  Born-Again Christian           Straight           1994
419                    Na           Straight           1979
420        Roman Catholic           Straight           1942
421              Buddhist           Bisexual           2000
422                Jewish           Straight           1976
423                    Na           Straight           1946
424        Roman Catholic           Straight           1977
425                    Na           Straight           1943
426                    Na           Straight           1958
427        Roman Catholic           Straight           1953
428                Jewish           Straight           1967
429                    Na           Straight           2005
430                    Na           Straight           2005
431                Jewish           Straight           1999
432                    Na                 Na           1969
433                    Na           Straight           2010
434                    Na           Straight           2001
435                    Na           Straight           1970
436                Jewish           Straight           2006
437        Roman Catholic           Straight           2009
438                    Na           Straight           1977
439                    Na           Straight           1999
440                    Na           Straight           1949

                       award                             movie  \
0              Best Director               Two Arabian Knights
1              Best Director                   The Divine Lady
2              Best Director    All Quiet on the Western Front
3              Best Director                            Skippy
4              Best Director                          Bad Girl
5              Best Director                         Cavalcade
6              Best Director             It Happened One Night
7              Best Director                      The Informer
8              Best Director            Mr. Deeds Goes to Town
9              Best Director                   The Awful Truth
10             Best Director        You Can't Take It with You
11             Best Director                Gone with the Wind
12             Best Director               The Grapes of Wrath
13             Best Director           How Green Was My Valley
14             Best Director                      Mrs. Miniver
15             Best Director                        Casablanca
16             Best Director                      Going My Way
17             Best Director                   West Side Story
18             Best Director                  The Lost Weekend
19             Best Director       The Best Years of Our Lives
20             Best Director             Gentleman's Agreement
21             Best Director  The Treasure of the Sierra Madre
22             Best Director           A Letter to Three Wives
23             Best Director                     All About Eve
24             Best Director                A Place in the Sun
25             Best Director                     The Quiet Man
26             Best Director             From Here to Eternity
27             Best Director                 On the Waterfront
28             Best Director                             Marty
29             Best Director                             Giant
..                       ...                               ...
411  Best Supporting Actress                          Precious
412  Best Supporting Actress                       The Fighter
413  Best Supporting Actress                          The Help
414  Best Supporting Actress                   Les MisÌ©rables
415  Best Supporting Actress                  12 Years a Slave
416            Best Director                     The Apartment
417             Best Actress                       Kitty Foyle
418               Best Actor                      Philadelphia
419            Best Director                   The Deer Hunter
420  Best Supporting Actress                     The Great Lie
421  Best Supporting Actress                 Girl, Interrupted
422  Best Supporting Actress                           Shampoo
423  Best Supporting Actress                   National Velvet
424             Best Actress                           Network
425    Best Supporting Actor                      Johnny Eager
426             Best Actress            The Three Faces of Eve
427               Best Actor                         High Noon
428             Best Actress   Who's Afraid of Virginia Woolf?
429             Best Actress               Million Dollar Baby
430             Best Actress               Million Dollar Baby
431             Best Actress               Shakespeare in Love
432    Best Supporting Actor             The Subject Was Roses
433  Best Supporting Actress                          Precious
434  Best Supporting Actress                           Pollock
435             Best Actress     The Prime of Miss Jean Brodie
436  Best Supporting Actress             The Constant Gardener
437            Best Director               Slumdog Millionaire
438    Best Supporting Actor           All the President's Men
439    Best Supporting Actor                        Affliction
440            Best Director  The Treasure of the Sierra Madre

                   person
0         Lewis Milestone
1             Frank Lloyd
2         Lewis Milestone
3           Norman Taurog
4           Frank Borzage
5             Frank Lloyd
6             Frank Capra
7               John Ford
8             Frank Capra
9             Leo McCarey
10            Frank Capra
11         Victor Fleming
12              John Ford
13              John Ford
14          William Wyler
15         Michael Curtiz
16            Leo McCarey
17         Jerome Robbins
18           Billy Wilder
19          William Wyler
20             Elia Kazan
21            John Huston
22   Joseph L. Mankiewicz
23   Joseph L. Mankiewicz
24         George Stevens
25              John Ford
26         Fred Zinnemann
27             Elia Kazan
28           Delbert Mann
29         George Stevens
..                    ...
411              Mo'Nique
412           Melissa Leo
413       Octavia Spencer
414         Anne Hathaway
415        Lupita Nyong'o
416          Billy Wilder
417         Ginger Rogers
418             Tom Hanks
419        Michael Cimino
420            Mary Astor
421        Angelina Jolie
422             Lee Grant
423           Anne Revere
424          Faye Dunaway
425            Van Heflin
426       Joanne Woodward
427           Gary Cooper
428      Elizabeth Taylor
429          Hilary Swank
430          Hilary Swank
431       Gwyneth Paltrow
432        Jack Albertson
433              Mo'Nique
434     Marcia Gay Harden
435          Maggie Smith
436          Rachel Weisz
437           Danny Boyle
438         Jason Robards
439          James Coburn
440           John Huston

[441 rows x 9 columns]

In [ ]:
# las columnas con nombre son un ColumnIndex

In [214]:
# si quisieramos seleccionar un indice podriamos hacer
oscars_byID=oscars.set_index(['person','year_of_award'])

In [215]:
oscars_byID

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                   date_of_birth race_ethnicity  \
person               year_of_award
Lewis Milestone      1927            30-Sep-1895          White
Frank Lloyd          1930             2-Feb-1886          White
Lewis Milestone      1931            30-Sep-1895          White
Norman Taurog        1932            23-Feb-1899          White
Frank Borzage        1933            23-Apr-1894          White
Frank Lloyd          1934             2-Feb-1886          White
Frank Capra          1935            18-May-1897          White
John Ford            1936             1-Feb-1894          White
Frank Capra          1937            18-May-1897          White
Leo McCarey          1938             3-Oct-1898          White
Frank Capra          1939            18-May-1897          White
Victor Fleming       1940            23-Feb-1883          White
John Ford            1941             1-Feb-1894          White
                     1942             1-Feb-1894          White
William Wyler        1943             1-Jul-1902          White
Michael Curtiz       1944            24-Dec-1886          White
Leo McCarey          1945             3-Oct-1898          White
Jerome Robbins       1962              11-Oct-18          White
Billy Wilder         1946              22-Jun-06          White
William Wyler        1947             1-Jul-1902          White
Elia Kazan           1948               7-Sep-09          White
John Huston          1949               5-Aug-06          White
Joseph L. Mankiewicz 1950              11-Feb-09          White
                     1951              11-Feb-09          White
George Stevens       1952              18-Dec-04          White
John Ford            1953             1-Feb-1894          White
Fred Zinnemann       1954              29-Apr-07          White
Elia Kazan           1955               7-Sep-09          White
Delbert Mann         1956              30-Jan-20          White
George Stevens       1957              18-Dec-04          White
...                                          ...            ...
Mo'Nique             2010              11-Dec-67          Black
Melissa Leo          2011              14-Sep-60          White
Octavia Spencer      2012              25-May-72          Black
Anne Hathaway        2013              12-Nov-82          White
Lupita Nyong'o       2014               1-Mar-83          Black
Billy Wilder         1961              22-Jun-06          White
Ginger Rogers        1941              16-Jul-11          White
Tom Hanks            1994               9-Jul-56          White
Michael Cimino       1979               3-Feb-39          White
Mary Astor           1942               3-May-06          White
Angelina Jolie       2000               4-Jun-75          White
Lee Grant            1976              31-Oct-27          White
Anne Revere          1946            25-Jun-1903          White
Faye Dunaway         1977              14-Jan-41          White
Van Heflin           1943              13-Dec-10          White
Joanne Woodward      1958              27-Feb-30          White
Gary Cooper          1953             7-May-1901          White
Elizabeth Taylor     1967              27-Feb-32          White
Hilary Swank         2005              30-Jul-74          White
                     2005              30-Jul-74          White
Gwyneth Paltrow      1999              27-Sep-72          White
Jack Albertson       1969              16-Jun-07          White
Mo'Nique             2010              11-Dec-67          Black
Marcia Gay Harden    2001              14-Aug-59          White
Maggie Smith         1970              28-Dec-34          White
Rachel Weisz         2006               7-Mar-71          White
Danny Boyle          2009              20-Oct-56          White
Jason Robards        1977              26-Jul-22          White
James Coburn         1999              31-Aug-28          White
John Huston          1949               5-Aug-06          White

                                                religion sexual_orientation  \
person               year_of_award
Lewis Milestone      1927                             Na           Straight
Frank Lloyd          1930                             Na           Straight
Lewis Milestone      1931                             Na           Straight
Norman Taurog        1932                             Na           Straight
Frank Borzage        1933                 Roman Catholic           Straight
Frank Lloyd          1934                             Na           Straight
Frank Capra          1935                 Roman Catholic           Straight
John Ford            1936                 Roman Catholic           Bisexual
Frank Capra          1937                 Roman Catholic           Straight
Leo McCarey          1938                             Na           Straight
Frank Capra          1939                 Roman Catholic           Straight
Victor Fleming       1940                             Na           Straight
John Ford            1941                 Roman Catholic           Bisexual
                     1942                 Roman Catholic           Bisexual
William Wyler        1943                             Na           Straight
Michael Curtiz       1944                             Na           Straight
Leo McCarey          1945                             Na           Straight
Jerome Robbins       1962                         Jewish                Gay
Billy Wilder         1946                         Jewish           Straight
William Wyler        1947                             Na           Straight
Elia Kazan           1948                             Na           Straight
John Huston          1949                             Na           Straight
Joseph L. Mankiewicz 1950                         Jewish           Straight
                     1951                         Jewish           Straight
George Stevens       1952                             Na           Straight
John Ford            1953                 Roman Catholic           Bisexual
Fred Zinnemann       1954                         Jewish           Straight
Elia Kazan           1955                             Na           Straight
Delbert Mann         1956                   Presbyterian           Straight
George Stevens       1957                             Na           Straight
...                                                  ...                ...
Mo'Nique             2010                             Na           Straight
Melissa Leo          2011                             Na           Straight
Octavia Spencer      2012                             Na                 Na
Anne Hathaway        2013                      Christian           Straight
Lupita Nyong'o       2014                             Na                 Na
Billy Wilder         1961                         Jewish           Straight
Ginger Rogers        1941              Christian Science           Straight
Tom Hanks            1994           Born-Again Christian           Straight
Michael Cimino       1979                             Na           Straight
Mary Astor           1942                 Roman Catholic           Straight
Angelina Jolie       2000                       Buddhist           Bisexual
Lee Grant            1976                         Jewish           Straight
Anne Revere          1946                             Na           Straight
Faye Dunaway         1977                 Roman Catholic           Straight
Van Heflin           1943                             Na           Straight
Joanne Woodward      1958                             Na           Straight
Gary Cooper          1953                 Roman Catholic           Straight
Elizabeth Taylor     1967                         Jewish           Straight
Hilary Swank         2005                             Na           Straight
                     2005                             Na           Straight
Gwyneth Paltrow      1999                         Jewish           Straight
Jack Albertson       1969                             Na                 Na
Mo'Nique             2010                             Na           Straight
Marcia Gay Harden    2001                             Na           Straight
Maggie Smith         1970                             Na           Straight
Rachel Weisz         2006                         Jewish           Straight
Danny Boyle          2009                 Roman Catholic           Straight
Jason Robards        1977                             Na           Straight
James Coburn         1999                             Na           Straight
John Huston          1949                             Na           Straight

                                                      award  \
person               year_of_award
Lewis Milestone      1927                     Best Director
Frank Lloyd          1930                     Best Director
Lewis Milestone      1931                     Best Director
Norman Taurog        1932                     Best Director
Frank Borzage        1933                     Best Director
Frank Lloyd          1934                     Best Director
Frank Capra          1935                     Best Director
John Ford            1936                     Best Director
Frank Capra          1937                     Best Director
Leo McCarey          1938                     Best Director
Frank Capra          1939                     Best Director
Victor Fleming       1940                     Best Director
John Ford            1941                     Best Director
                     1942                     Best Director
William Wyler        1943                     Best Director
Michael Curtiz       1944                     Best Director
Leo McCarey          1945                     Best Director
Jerome Robbins       1962                     Best Director
Billy Wilder         1946                     Best Director
William Wyler        1947                     Best Director
Elia Kazan           1948                     Best Director
John Huston          1949                     Best Director
Joseph L. Mankiewicz 1950                     Best Director
                     1951                     Best Director
George Stevens       1952                     Best Director
John Ford            1953                     Best Director
Fred Zinnemann       1954                     Best Director
Elia Kazan           1955                     Best Director
Delbert Mann         1956                     Best Director
George Stevens       1957                     Best Director
...                                                     ...
Mo'Nique             2010           Best Supporting Actress
Melissa Leo          2011           Best Supporting Actress
Octavia Spencer      2012           Best Supporting Actress
Anne Hathaway        2013           Best Supporting Actress
Lupita Nyong'o       2014           Best Supporting Actress
Billy Wilder         1961                     Best Director
Ginger Rogers        1941                      Best Actress
Tom Hanks            1994                        Best Actor
Michael Cimino       1979                     Best Director
Mary Astor           1942           Best Supporting Actress
Angelina Jolie       2000           Best Supporting Actress
Lee Grant            1976           Best Supporting Actress
Anne Revere          1946           Best Supporting Actress
Faye Dunaway         1977                      Best Actress
Van Heflin           1943             Best Supporting Actor
Joanne Woodward      1958                      Best Actress
Gary Cooper          1953                        Best Actor
Elizabeth Taylor     1967                      Best Actress
Hilary Swank         2005                      Best Actress
                     2005                      Best Actress
Gwyneth Paltrow      1999                      Best Actress
Jack Albertson       1969             Best Supporting Actor
Mo'Nique             2010           Best Supporting Actress
Marcia Gay Harden    2001           Best Supporting Actress
Maggie Smith         1970                      Best Actress
Rachel Weisz         2006           Best Supporting Actress
Danny Boyle          2009                     Best Director
Jason Robards        1977             Best Supporting Actor
James Coburn         1999             Best Supporting Actor
John Huston          1949                     Best Director

                                                               movie
person               year_of_award
Lewis Milestone      1927                        Two Arabian Knights
Frank Lloyd          1930                            The Divine Lady
Lewis Milestone      1931             All Quiet on the Western Front
Norman Taurog        1932                                     Skippy
Frank Borzage        1933                                   Bad Girl
Frank Lloyd          1934                                  Cavalcade
Frank Capra          1935                      It Happened One Night
John Ford            1936                               The Informer
Frank Capra          1937                     Mr. Deeds Goes to Town
Leo McCarey          1938                            The Awful Truth
Frank Capra          1939                 You Can't Take It with You
Victor Fleming       1940                         Gone with the Wind
John Ford            1941                        The Grapes of Wrath
                     1942                    How Green Was My Valley
William Wyler        1943                               Mrs. Miniver
Michael Curtiz       1944                                 Casablanca
Leo McCarey          1945                               Going My Way
Jerome Robbins       1962                            West Side Story
Billy Wilder         1946                           The Lost Weekend
William Wyler        1947                The Best Years of Our Lives
Elia Kazan           1948                      Gentleman's Agreement
John Huston          1949           The Treasure of the Sierra Madre
Joseph L. Mankiewicz 1950                    A Letter to Three Wives
                     1951                              All About Eve
George Stevens       1952                         A Place in the Sun
John Ford            1953                              The Quiet Man
Fred Zinnemann       1954                      From Here to Eternity
Elia Kazan           1955                          On the Waterfront
Delbert Mann         1956                                      Marty
George Stevens       1957                                      Giant
...                                                              ...
Mo'Nique             2010                                   Precious
Melissa Leo          2011                                The Fighter
Octavia Spencer      2012                                   The Help
Anne Hathaway        2013                            Les MisÌ©rables
Lupita Nyong'o       2014                           12 Years a Slave
Billy Wilder         1961                              The Apartment
Ginger Rogers        1941                                Kitty Foyle
Tom Hanks            1994                               Philadelphia
Michael Cimino       1979                            The Deer Hunter
Mary Astor           1942                              The Great Lie

In [216]:
print(oscars_byID)

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                   date_of_birth race_ethnicity  \
person               year_of_award
Lewis Milestone      1927            30-Sep-1895          White
Frank Lloyd          1930             2-Feb-1886          White
Lewis Milestone      1931            30-Sep-1895          White
Norman Taurog        1932            23-Feb-1899          White
Frank Borzage        1933            23-Apr-1894          White
Frank Lloyd          1934             2-Feb-1886          White
Frank Capra          1935            18-May-1897          White
John Ford            1936             1-Feb-1894          White
Frank Capra          1937            18-May-1897          White
Leo McCarey          1938             3-Oct-1898          White
Frank Capra          1939            18-May-1897          White
Victor Fleming       1940            23-Feb-1883          White
John Ford            1941             1-Feb-1894          White
                     1942             1-Feb-1894          White
William Wyler        1943             1-Jul-1902          White
Michael Curtiz       1944            24-Dec-1886          White
Leo McCarey          1945             3-Oct-1898          White
Jerome Robbins       1962              11-Oct-18          White
Billy Wilder         1946              22-Jun-06          White
William Wyler        1947             1-Jul-1902          White
Elia Kazan           1948               7-Sep-09          White
John Huston          1949               5-Aug-06          White
Joseph L. Mankiewicz 1950              11-Feb-09          White
                     1951              11-Feb-09          White
George Stevens       1952              18-Dec-04          White
John Ford            1953             1-Feb-1894          White
Fred Zinnemann       1954              29-Apr-07          White
Elia Kazan           1955               7-Sep-09          White
Delbert Mann         1956              30-Jan-20          White
George Stevens       1957              18-Dec-04          White
...                                          ...            ...
Mo'Nique             2010              11-Dec-67          Black
Melissa Leo          2011              14-Sep-60          White
Octavia Spencer      2012              25-May-72          Black
Anne Hathaway        2013              12-Nov-82          White
Lupita Nyong'o       2014               1-Mar-83          Black
Billy Wilder         1961              22-Jun-06          White
Ginger Rogers        1941              16-Jul-11          White
Tom Hanks            1994               9-Jul-56          White
Michael Cimino       1979               3-Feb-39          White
Mary Astor           1942               3-May-06          White
Angelina Jolie       2000               4-Jun-75          White
Lee Grant            1976              31-Oct-27          White
Anne Revere          1946            25-Jun-1903          White
Faye Dunaway         1977              14-Jan-41          White
Van Heflin           1943              13-Dec-10          White
Joanne Woodward      1958              27-Feb-30          White
Gary Cooper          1953             7-May-1901          White
Elizabeth Taylor     1967              27-Feb-32          White
Hilary Swank         2005              30-Jul-74          White
                     2005              30-Jul-74          White
Gwyneth Paltrow      1999              27-Sep-72          White
Jack Albertson       1969              16-Jun-07          White
Mo'Nique             2010              11-Dec-67          Black
Marcia Gay Harden    2001              14-Aug-59          White
Maggie Smith         1970              28-Dec-34          White
Rachel Weisz         2006               7-Mar-71          White
Danny Boyle          2009              20-Oct-56          White
Jason Robards        1977              26-Jul-22          White
James Coburn         1999              31-Aug-28          White
John Huston          1949               5-Aug-06          White

                                                religion sexual_orientation  \
person               year_of_award
Lewis Milestone      1927                             Na           Straight
Frank Lloyd          1930                             Na           Straight
Lewis Milestone      1931                             Na           Straight
Norman Taurog        1932                             Na           Straight
Frank Borzage        1933                 Roman Catholic           Straight
Frank Lloyd          1934                             Na           Straight
Frank Capra          1935                 Roman Catholic           Straight
John Ford            1936                 Roman Catholic           Bisexual
Frank Capra          1937                 Roman Catholic           Straight
Leo McCarey          1938                             Na           Straight
Frank Capra          1939                 Roman Catholic           Straight
Victor Fleming       1940                             Na           Straight
John Ford            1941                 Roman Catholic           Bisexual
                     1942                 Roman Catholic           Bisexual
William Wyler        1943                             Na           Straight
Michael Curtiz       1944                             Na           Straight
Leo McCarey          1945                             Na           Straight
Jerome Robbins       1962                         Jewish                Gay
Billy Wilder         1946                         Jewish           Straight
William Wyler        1947                             Na           Straight
Elia Kazan           1948                             Na           Straight
John Huston          1949                             Na           Straight
Joseph L. Mankiewicz 1950                         Jewish           Straight
                     1951                         Jewish           Straight
George Stevens       1952                             Na           Straight
John Ford            1953                 Roman Catholic           Bisexual
Fred Zinnemann       1954                         Jewish           Straight
Elia Kazan           1955                             Na           Straight
Delbert Mann         1956                   Presbyterian           Straight
George Stevens       1957                             Na           Straight
...                                                  ...                ...
Mo'Nique             2010                             Na           Straight
Melissa Leo          2011                             Na           Straight
Octavia Spencer      2012                             Na                 Na
Anne Hathaway        2013                      Christian           Straight
Lupita Nyong'o       2014                             Na                 Na
Billy Wilder         1961                         Jewish           Straight
Ginger Rogers        1941              Christian Science           Straight
Tom Hanks            1994           Born-Again Christian           Straight
Michael Cimino       1979                             Na           Straight
Mary Astor           1942                 Roman Catholic           Straight
Angelina Jolie       2000                       Buddhist           Bisexual
Lee Grant            1976                         Jewish           Straight
Anne Revere          1946                             Na           Straight
Faye Dunaway         1977                 Roman Catholic           Straight
Van Heflin           1943                             Na           Straight
Joanne Woodward      1958                             Na           Straight
Gary Cooper          1953                 Roman Catholic           Straight
Elizabeth Taylor     1967                         Jewish           Straight
Hilary Swank         2005                             Na           Straight
                     2005                             Na           Straight
Gwyneth Paltrow      1999                         Jewish           Straight
Jack Albertson       1969                             Na                 Na
Mo'Nique             2010                             Na           Straight
Marcia Gay Harden    2001                             Na           Straight
Maggie Smith         1970                             Na           Straight
Rachel Weisz         2006                         Jewish           Straight
Danny Boyle          2009                 Roman Catholic           Straight
Jason Robards        1977                             Na           Straight
James Coburn         1999                             Na           Straight
John Huston          1949                             Na           Straight

                                                      award  \
person               year_of_award
Lewis Milestone      1927                     Best Director
Frank Lloyd          1930                     Best Director
Lewis Milestone      1931                     Best Director
Norman Taurog        1932                     Best Director
Frank Borzage        1933                     Best Director
Frank Lloyd          1934                     Best Director
Frank Capra          1935                     Best Director
John Ford            1936                     Best Director
Frank Capra          1937                     Best Director
Leo McCarey          1938                     Best Director
Frank Capra          1939                     Best Director
Victor Fleming       1940                     Best Director
John Ford            1941                     Best Director
                     1942                     Best Director
William Wyler        1943                     Best Director
Michael Curtiz       1944                     Best Director
Leo McCarey          1945                     Best Director
Jerome Robbins       1962                     Best Director
Billy Wilder         1946                     Best Director
William Wyler        1947                     Best Director
Elia Kazan           1948                     Best Director
John Huston          1949                     Best Director
Joseph L. Mankiewicz 1950                     Best Director
                     1951                     Best Director
George Stevens       1952                     Best Director
John Ford            1953                     Best Director
Fred Zinnemann       1954                     Best Director
Elia Kazan           1955                     Best Director
Delbert Mann         1956                     Best Director
George Stevens       1957                     Best Director
...                                                     ...
Mo'Nique             2010           Best Supporting Actress
Melissa Leo          2011           Best Supporting Actress
Octavia Spencer      2012           Best Supporting Actress
Anne Hathaway        2013           Best Supporting Actress
Lupita Nyong'o       2014           Best Supporting Actress
Billy Wilder         1961                     Best Director
Ginger Rogers        1941                      Best Actress
Tom Hanks            1994                        Best Actor
Michael Cimino       1979                     Best Director
Mary Astor           1942           Best Supporting Actress
Angelina Jolie       2000           Best Supporting Actress
Lee Grant            1976           Best Supporting Actress
Anne Revere          1946           Best Supporting Actress
Faye Dunaway         1977                      Best Actress
Van Heflin           1943             Best Supporting Actor
Joanne Woodward      1958                      Best Actress
Gary Cooper          1953                        Best Actor
Elizabeth Taylor     1967                      Best Actress
Hilary Swank         2005                      Best Actress
                     2005                      Best Actress
Gwyneth Paltrow      1999                      Best Actress
Jack Albertson       1969             Best Supporting Actor
Mo'Nique             2010           Best Supporting Actress
Marcia Gay Harden    2001           Best Supporting Actress
Maggie Smith         1970                      Best Actress
Rachel Weisz         2006           Best Supporting Actress
Danny Boyle          2009                     Best Director
Jason Robards        1977             Best Supporting Actor
James Coburn         1999             Best Supporting Actor
John Huston          1949                     Best Director

                                                               movie
person               year_of_award
Lewis Milestone      1927                        Two Arabian Knights
Frank Lloyd          1930                            The Divine Lady
Lewis Milestone      1931             All Quiet on the Western Front
Norman Taurog        1932                                     Skippy
Frank Borzage        1933                                   Bad Girl
Frank Lloyd          1934                                  Cavalcade
Frank Capra          1935                      It Happened One Night
John Ford            1936                               The Informer
Frank Capra          1937                     Mr. Deeds Goes to Town
Leo McCarey          1938                            The Awful Truth
Frank Capra          1939                 You Can't Take It with You
Victor Fleming       1940                         Gone with the Wind
John Ford            1941                        The Grapes of Wrath
                     1942                    How Green Was My Valley
William Wyler        1943                               Mrs. Miniver
Michael Curtiz       1944                                 Casablanca
Leo McCarey          1945                               Going My Way
Jerome Robbins       1962                            West Side Story
Billy Wilder         1946                           The Lost Weekend
William Wyler        1947                The Best Years of Our Lives
Elia Kazan           1948                      Gentleman's Agreement
John Huston          1949           The Treasure of the Sierra Madre
Joseph L. Mankiewicz 1950                    A Letter to Three Wives
                     1951                              All About Eve
George Stevens       1952                         A Place in the Sun
John Ford            1953                              The Quiet Man
Fred Zinnemann       1954                      From Here to Eternity
Elia Kazan           1955                          On the Waterfront
Delbert Mann         1956                                      Marty
George Stevens       1957                                      Giant
...                                                              ...
Mo'Nique             2010                                   Precious
Melissa Leo          2011                                The Fighter
Octavia Spencer      2012                                   The Help
Anne Hathaway        2013                            Les MisÌ©rables
Lupita Nyong'o       2014                           12 Years a Slave
Billy Wilder         1961                              The Apartment
Ginger Rogers        1941                                Kitty Foyle
Tom Hanks            1994                               Philadelphia
Michael Cimino       1979                            The Deer Hunter
Mary Astor           1942                              The Great Lie

In [217]:
oscars_byID.count()

birthplace            441
date_of_birth         441
race_ethnicity        441
religion              441
sexual_orientation    441
award                 441
movie                 441
dtype: int64

In [219]:
oscars_byID =pd.read_csv('Oscars-demographics-DFE.csv', encoding='latin-1', index_col=['person','year_of_award'])

In [220]:
oscars_byID.tail()

,,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
person,year_of_award,,,,,,,,,,,,,,,,,,,,,
Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
James Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

Al igual como se crean, los indices tambien se pueden eliminar

In [222]:
oscars_byID.reset_index()

,person,year_of_award,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,Lewis Milestone,1927,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0000,30-Sep-1895,...,1.0000,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,NaN,NaN,NaN,NaN
1,Frank Lloyd,1930,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0000,2-Feb-1886,...,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,NaN,NaN,NaN,NaN
2,Lewis Milestone,1931,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0000,30-Sep-1895,...,0.6667,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,NaN,NaN,NaN,NaN
3,Norman Taurog,1932,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0000,23-Feb-1899,...,1.0000,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,NaN,NaN,NaN,NaN
4,Frank Borzage,1933,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0000,23-Apr-1894,...,1.0000,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,NaN,NaN,NaN,NaN
5,Frank Lloyd,1934,670454358,False,finalized,3,2/10/15 3:50,"Glasgow, Scotland",1.0000,2-Feb-1886,...,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,Cavalcade,NaN,NaN,NaN,NaN
6,Frank Capra,1935,670454359,False,finalized,3,2/10/15 2:07,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,It Happened One Night,NaN,NaN,NaN,NaN
7,John Ford,1936,670454360,False,finalized,3,2/10/15 1:46,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Informer,NaN,NaN,NaN,NaN
8,Frank Capra,1937,670454361,False,finalized,3,2/10/15 1:47,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,Mr. Deeds Goes to Town,NaN,NaN,NaN,NaN
9,Leo McCarey,1938,670454362,False,finalized,3,2/10/15 2:05,"Los Angeles, Ca",1.0000,3-Oct-1898,...,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,The Awful Truth,NaN,NaN,NaN,NaN
10,Frank Capra,1939,670454363,False,finalized,3,2/10/15 2:04,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,...,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,NaN,NaN,You Can't Take It with You,NaN,NaN,NaN,NaN
11,Victor Fleming,1940,670454364,False,finalized,3,2/10/15 2:10,"Pasadena, Ca",1.0000,23-Feb-1883,...,1.0000,Best Director,http://www.nndb.com/people/416/000041293/,NaN,NaN,Gone with the Wind,NaN,NaN,NaN,NaN
12,John Ford,1941,670454365,False,finalized,3,2/10/15 2:12,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Grapes of Wrath,NaN,NaN,NaN,NaN
13,John Ford,1942,670454366,False,finalized,3,2/10/15 2:02,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,How Green Was My Valley,NaN,NaN,NaN,NaN
14,William Wyler,1943,670454367,False,finalized,3,2/10/15 3:57,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,...,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,Mrs. Miniver,NaN,NaN,NaN,NaN
15,Michael Curtiz,1944,670454368,False,finalized,3,2/10/15 2:02,"Budapest, Hungary",1.0000,24-Dec-1886,...,1.0000,Best Director,http://www.nndb.com/people/676/000032580/,NaN,NaN,Casablanca,NaN,NaN,NaN,NaN
16,Leo McCarey,1945,670454369,False,finalized,3,2/10/15 2:29,"Los Angeles, Ca",1.0000,3-Oct-1898,...,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,NaN,NaN,Going My Way,NaN,NaN,NaN,NaN
17,Jerome Robbins,1962,670454370,False,finalized,3,2/10/15 1:55,New York City,1.0000,11-Oct-18,...,1.0000,Best Director,http://www.nndb.com/people/281/000064089/,NaN,NaN,West Side Story,NaN,NaN,NaN,NaN
18,Billy Wilder,1946,670454371,False,finalized,3,2/10/15 4:02,"Sucha, Galicia, Austria",0.6667,22-Jun-06,...,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Lost Weekend,NaN,NaN,NaN,NaN
19,William Wyler,1947,670454372,False,finalized,3,2/10/15 2:12,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,...,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,NaN,NaN,The Best Years of Our Lives,NaN,NaN,NaN,NaN
20,Elia Kazan,1948,670454373,False,finalized,3,2/10/15 1:46,"Istanbul, Turkey",1.0000,7-Sep-09,...,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,Gentleman's Agreement,NaN,NaN,NaN,NaN
21,John Huston,1949,670454374,True,golden,82,NaN,"Nevada, Mo",1.0000,5-Aug-06,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,5-Aug-06,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN
22,Joseph L. Mankiewicz,1950,670454375,False,finalized,3,2/10/15 3:50,"Wilkes-Barre, Pa",1.0000,11-Feb-09,...,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,A Letter to Three Wives,NaN,NaN,NaN,NaN
23,Joseph L. Mankiewicz,1951,670454376,False,finalized,3,2/10/15 1:51,"Wilkes-Barre, Pa",1.0000,11-Feb-09,...,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,NaN,NaN,All About Eve,NaN,NaN,NaN,NaN
24,George Stevens,1952,670454377,False,finalized,3,2/10/15 2:15,"Oakland, Ca",1.0000,18-Dec-04,...,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,NaN,NaN,A Place in the Sun,NaN,NaN,NaN,NaN
25,John Ford,1953,670454378,False,finalized,3,2/10/15 2:15,"Cape Elizabeth, Me",1.0000,1-Feb-1894,...,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,NaN,NaN,The Quiet Man,NaN,NaN,NaN,NaN
26,Fred Zinnemann,1954,670454379,False,finalized,3,2/10/15 1:57,"Vienna, Austria",1.0000,29-Apr-07,...,1.0000,Best Director,http://www.nndb.com/people/538/000032442/,NaN,NaN,From Here to Eternity,NaN,NaN,NaN,NaN
27,Elia Kazan,1955,670454380,False,finalized,3,2/10/15 3:50,"Istanbul, Turkey",1.0000,7-Sep-09,...,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,NaN,NaN,On the Waterfront,NaN,NaN,NaN,NaN
28,Delbert Mann,1956,670454381,False,finalized,3,2/10/15 3:53,"Lawrence, Ks",1.0000,30-Jan-20,...,1.0000,Best Director,http://www.nndb.com/people/384/000044252/,NaN,NaN,Marty,NaN,NaN,NaN,NaN
29,George Stevens,1957,670454382,False,finalized,3,2/10/15 3:50,"Oakland, Ca",1.0000,18-Dec-04,...,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,NaN,NaN,Giant,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,Mo'Nique,2010,670454764,True,golden,86,NaN,"Woodlawn, Md",1.0000,11-Dec-67,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,11-Dec-67,Precious,Black,NaN,NaN,NaN
412,Melissa Leo,2011,670454765,False,finalized,3,2/10/15 1:56,New York City,1.0000,14-Sep-60,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/327/000042201/,NaN,NaN,The Fighter,NaN,NaN,NaN,NaN
413,Octavia Spencer,2012,670454766,False,finalized,3,2/10/15 2:18,"Montgomery, Al",1.0000,25-May-72,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/304/000281458/,NaN,NaN,The Help,NaN,NaN,NaN,NaN
414,Anne Hathaway,2013,670454767,False,finalized,3,2/10/15 2:18,"Brooklyn, Ny",1.0000,12-Nov-82,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/220/000032124/,NaN,NaN,Les MisÌ©rables,NaN,NaN,NaN,NaN
415,Lupita Nyong'o,2014,670454768,False,finalized,3,2/10/15 2:10,"Mexico City, Mexico",1.0000,1-Mar-83,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/570/000380427/,NaN,NaN,12 Years a Slave,NaN,NaN,NaN,NaN
416,Billy Wilder,1961,670927629,False,finalized,3,2/10/15 2:02,"Sucha, Galicia, Austria",1.0000,22-Jun-06,...,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,NaN,NaN,The Apartment,NaN,NaN,NaN,NaN
417,Ginger Rogers,1941,670939613,False,finalized,3,2/10/15 1:53,"Independence, Mo",1.0000,16-Jul-11,...,1.0000,Best Actress,http://www.nndb.com/people/635/000043506/,NaN,NaN,Kitty Foyle,NaN,NaN,NaN,NaN
418,Tom Hanks,1994,670944094,False,finalized,3,2/10/15 2:18,"Concord, Ca",1.0000,9-Jul-56,...,1.0000,Best Actor,http://www.nndb.com/people/687/000022621/,NaN,NaN,Philadelphia,NaN,NaN,NaN,NaN
419,Michael Cimino,1979,670944168,False,finalized,3,2/10/15 3:55,New York City,1.0000,3-Feb-39,...,0.6667,Best Director,http://www.nndb.com/people/810/000043681/,NaN,NaN,The Deer Hunter,NaN,NaN,NaN,NaN
420,Mary Astor,1942,670944316,False,finalized,3,2/10/15 2:05,"Quincy, Il",1.0000,3-May-06,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/690/000042564/,NaN,NaN,The Great Lie,NaN,NaN,NaN,NaN
421,Angelina Jolie,2000,670944478,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,4-Jun-75,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/493/000023424/,NaN,NaN,"Girl, Interrupted",NaN,NaN,NaN,NaN
422,Lee Grant,1976,670944543,False,finalized,3,2/10/15 2:12,New York City,1.0000,31-Oct-27,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/409/000032313/,NaN,NaN,Shampoo,NaN,NaN,NaN,NaN
423,Anne Revere,1946,670944623,False,finalized,3,2/10/15 2:11,New York City,1.0000,25-Jun-1903,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/081/000063889/,NaN,NaN,National Velvet,NaN,NaN,NaN,NaN
424,Faye Dunaway,1977,670944674,False,finalized,3,2/10/15 2:05,"Bascom, Fl",1.0000,14-Jan-41,...,1.0000,Best Actress,http://www.nndb.com/people/884/000022818/,NaN,NaN,Network,NaN,NaN,NaN,NaN
425,Van Heflin,1943,670944755,False,finalized,3,2/10/15 2:04,"Walters, Ok",1.0000,13-Dec-10,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/680/000042554/,NaN,NaN,Johnny Eager,NaN,NaN,NaN,NaN
426,Joanne Woodward,1958,670944822,False,finalized,3,2/10/15 4:14,"Thomasville, Ga",1.0000,27-Feb-30,...,1.0000,Best Actress,http://www.nndb.com/people/747/000043618/,NaN,NaN,The Three Faces of Eve,NaN,NaN,NaN,NaN
427,Gary Cooper,1953,670944835,False,finalized,3,2/10/15 2:08,"Helena, Mt",1.0000,7-May-1901,...,1.0000,Best Actor,http://www.nndb.com/people/740/000031647/,NaN,NaN,High Noon,NaN,NaN,NaN,NaN
428,Elizabeth Taylor,1967,670944920,False,finalized,3,2/10/15 3:58,"London, England",1.0000,27-Feb-32,...,1.0000,Best Actress,http://www.nndb.com/people/624/000023555/,NaN,NaN,Who's Afraid of Virginia Woolf?,NaN,NaN,NaN,NaN
429,Hilary Swank,2005,670944948,False,finalized,3,2/10/15 2:06,"Lincoln, Ne",1.0000,30-Jul-74,...,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,NaN,NaN,NaN,NaN
430,Hilary Swank,2005,670945043,True,golden,86,NaN,"Lincoln, Ne",1.0000,30-Jul-74,...,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,NaN,NaN,Million Dollar Baby,NaN,NaN,NaN,NaN
431,Gwyneth Paltrow,1999,670945693,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,27-Sep-72,...,1.0000,Best Actress,http://www.nndb.com/people/592/000023523/,NaN,NaN,Shakespeare in Love,NaN,NaN,NaN,NaN
432,Jack Albertson,1969,670945790,False,finalized,3,2/10/15 2:08,"Malden, Ma",1.0000,16-Jun-07,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/559/000049412/,NaN,NaN,The Subject Was Roses,NaN,NaN,NaN,NaN
433,Mo'Nique,2010,670945834,False,finalized,3,2/10/15 2:07,"Woodlawn, Md",1.0000,11-Dec-67,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,NaN,NaN,Precious,NaN,NaN,NaN,NaN
434,Marcia Gay Harden,2001,670945895,False,finalized,3,2/10/15 2:13,"La Jolla, Ca",1.0000,14-Aug-59,...,1.0000,Best Supporting Actress,http://www.nndb.com/people/641/000025566/,NaN,NaN,Pollock,NaN,NaN,NaN,NaN
435,Maggie Smith,1970,670946199,False,finalized,3,2/10/15 2:03,"Ilford, Essex, England",1.0000,28-Dec-34,...,1.0000,Best Actress,http://www.nndb.com/people/260/000030170/,NaN,NaN,The Prime of Miss Jean Brodie,NaN,NaN,NaN,NaN
436,Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0000,7-Mar-71,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
437,Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0000,20-Oct-56,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
438,Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0000,26-Jul-22,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
439,James Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0000,31-Aug-28,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
440,John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0000,5-Aug-06,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

** TAMBIEN SE PUEDE DEJAR EL INDICE Y LAS COLUMNAS.
Para ello usamos set_index con el parametro drop=False

In [224]:
oscars_byID=oscars.set_index(['person','year_of_award'],drop=False)

In [226]:
# Aqui podemos ver que se mantienen las columas 'person' y 'year_of_award' a pesar que son tratados tambien como indices
oscars_byID

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                   date_of_birth race_ethnicity  \
person               year_of_award
Lewis Milestone      1927            30-Sep-1895          White
Frank Lloyd          1930             2-Feb-1886          White
Lewis Milestone      1931            30-Sep-1895          White
Norman Taurog        1932            23-Feb-1899          White
Frank Borzage        1933            23-Apr-1894          White
Frank Lloyd          1934             2-Feb-1886          White
Frank Capra          1935            18-May-1897          White
John Ford            1936             1-Feb-1894          White
Frank Capra          1937            18-May-1897          White
Leo McCarey          1938             3-Oct-1898          White
Frank Capra          1939            18-May-1897          White
Victor Fleming       1940            23-Feb-1883          White
John Ford            1941             1-Feb-1894          White
                     1942             1-Feb-1894          White
William Wyler        1943             1-Jul-1902          White
Michael Curtiz       1944            24-Dec-1886          White
Leo McCarey          1945             3-Oct-1898          White
Jerome Robbins       1962              11-Oct-18          White
Billy Wilder         1946              22-Jun-06          White
William Wyler        1947             1-Jul-1902          White
Elia Kazan           1948               7-Sep-09          White
John Huston          1949               5-Aug-06          White
Joseph L. Mankiewicz 1950              11-Feb-09          White
                     1951              11-Feb-09          White
George Stevens       1952              18-Dec-04          White
John Ford            1953             1-Feb-1894          White
Fred Zinnemann       1954              29-Apr-07          White
Elia Kazan           1955               7-Sep-09          White
Delbert Mann         1956              30-Jan-20          White
George Stevens       1957              18-Dec-04          White
...                                          ...            ...
Mo'Nique             2010              11-Dec-67          Black
Melissa Leo          2011              14-Sep-60          White
Octavia Spencer      2012              25-May-72          Black
Anne Hathaway        2013              12-Nov-82          White
Lupita Nyong'o       2014               1-Mar-83          Black
Billy Wilder         1961              22-Jun-06          White
Ginger Rogers        1941              16-Jul-11          White
Tom Hanks            1994               9-Jul-56          White
Michael Cimino       1979               3-Feb-39          White
Mary Astor           1942               3-May-06          White
Angelina Jolie       2000               4-Jun-75          White
Lee Grant            1976              31-Oct-27          White
Anne Revere          1946            25-Jun-1903          White
Faye Dunaway         1977              14-Jan-41          White
Van Heflin           1943              13-Dec-10          White
Joanne Woodward      1958              27-Feb-30          White
Gary Cooper          1953             7-May-1901          White
Elizabeth Taylor     1967              27-Feb-32          White
Hilary Swank         2005              30-Jul-74          White
                     2005              30-Jul-74          White
Gwyneth Paltrow      1999              27-Sep-72          White
Jack Albertson       1969              16-Jun-07          White
Mo'Nique             2010              11-Dec-67          Black
Marcia Gay Harden    2001              14-Aug-59          White
Maggie Smith         1970              28-Dec-34          White
Rachel Weisz         2006               7-Mar-71          White
Danny Boyle          2009              20-Oct-56          White
Jason Robards        1977              26-Jul-22          White
James Coburn         1999              31-Aug-28          White
John Huston          1949               5-Aug-06          White

                                                religion sexual_orientation  \
person               year_of_award
Lewis Milestone      1927                             Na           Straight
Frank Lloyd          1930                             Na           Straight
Lewis Milestone      1931                             Na           Straight
Norman Taurog        1932                             Na           Straight
Frank Borzage        1933                 Roman Catholic           Straight
Frank Lloyd          1934                             Na           Straight
Frank Capra          1935                 Roman Catholic           Straight
John Ford            1936                 Roman Catholic           Bisexual
Frank Capra          1937                 Roman Catholic           Straight
Leo McCarey          1938                             Na           Straight
Frank Capra          1939                 Roman Catholic           Straight
Victor Fleming       1940                             Na           Straight
John Ford            1941                 Roman Catholic           Bisexual
                     1942                 Roman Catholic           Bisexual
William Wyler        1943                             Na           Straight
Michael Curtiz       1944                             Na           Straight
Leo McCarey          1945                             Na           Straight
Jerome Robbins       1962                         Jewish                Gay
Billy Wilder         1946                         Jewish           Straight
William Wyler        1947                             Na           Straight
Elia Kazan           1948                             Na           Straight
John Huston          1949                             Na           Straight
Joseph L. Mankiewicz 1950                         Jewish           Straight
                     1951                         Jewish           Straight
George Stevens       1952                             Na           Straight
John Ford            1953                 Roman Catholic           Bisexual
Fred Zinnemann       1954                         Jewish           Straight
Elia Kazan           1955                             Na           Straight
Delbert Mann         1956                   Presbyterian           Straight
George Stevens       1957                             Na           Straight
...                                                  ...                ...
Mo'Nique             2010                             Na           Straight
Melissa Leo          2011                             Na           Straight
Octavia Spencer      2012                             Na                 Na
Anne Hathaway        2013                      Christian           Straight
Lupita Nyong'o       2014                             Na                 Na
Billy Wilder         1961                         Jewish           Straight
Ginger Rogers        1941              Christian Science           Straight
Tom Hanks            1994           Born-Again Christian           Straight
Michael Cimino       1979                             Na           Straight
Mary Astor           1942                 Roman Catholic           Straight
Angelina Jolie       2000                       Buddhist           Bisexual
Lee Grant            1976                         Jewish           Straight
Anne Revere          1946                             Na           Straight
Faye Dunaway         1977                 Roman Catholic           Straight
Van Heflin           1943                             Na           Straight
Joanne Woodward      1958                             Na           Straight
Gary Cooper          1953                 Roman Catholic           Straight
Elizabeth Taylor     1967                         Jewish           Straight
Hilary Swank         2005                             Na           Straight
                     2005                             Na           Straight
Gwyneth Paltrow      1999                         Jewish           Straight
Jack Albertson       1969                             Na                 Na
Mo'Nique             2010                             Na           Straight
Marcia Gay Harden    2001                             Na           Straight
Maggie Smith         1970                             Na           Straight
Rachel Weisz         2006                         Jewish           Straight
Danny Boyle          2009                 Roman Catholic           Straight
Jason Robards        1977                             Na           Straight
James Coburn         1999                             Na           Straight
John Huston          1949                             Na           Straight

                                    year_of_award                    award  \
person               year_of_award
Lewis Milestone      1927                    1927            Best Director
Frank Lloyd          1930                    1930            Best Director
Lewis Milestone      1931                    1931            Best Director
Norman Taurog        1932                    1932            Best Director
Frank Borzage        1933                    1933            Best Director
Frank Lloyd          1934                    1934            Best Director
Frank Capra          1935                    1935            Best Director
John Ford            1936                    1936            Best Director
Frank Capra          1937                    1937            Best Director
Leo McCarey          1938                    1938            Best Director
Frank Capra          1939                    1939            Best Director
Victor Fleming       1940                    1940            Best Director
John Ford            1941                    1941            Best Director
                     1942                    1942            Best Director
William Wyler        1943                    1943            Best Director
Michael Curtiz       1944                    1944            Best Director
Leo McCarey          1945                    1945            Best Director
Jerome Robbins       1962                    1962            Best Director
Billy Wilder         1946                    1946            Best Director
William Wyler        1947                    1947            Best Director
Elia Kazan           1948                    1948            Best Director
John Huston          1949                    1949            Best Director
Joseph L. Mankiewicz 1950                    1950            Best Director
                     1951                    1951            Best Director
George Stevens       1952                    1952            Best Director
John Ford            1953                    1953            Best Director
Fred Zinnemann       1954                    1954            Best Director
Elia Kazan           1955                    1955            Best Director
Delbert Mann         1956                    1956            Best Director
George Stevens       1957                    1957            Best Director
...                                           ...                      ...
Mo'Nique             2010                    2010  Best Supporting Actress
Melissa Leo          2011                    2011  Best Supporting Actress
Octavia Spencer      2012                    2012  Best Supporting Actress
Anne Hathaway        2013                    2013  Best Supporting Actress
Lupita Nyong'o       2014                    2014  Best Supporting Actress
Billy Wilder         1961                    1961            Best Director
Ginger Rogers        1941                    1941             Best Actress
Tom Hanks            1994                    1994               Best Actor
Michael Cimino       1979                    1979            Best Director
Mary Astor           1942                    1942  Best Supporting Actress
Angelina Jolie       2000                    2000  Best Supporting Actress
Lee Grant            1976                    1976  Best Supporting Actress
Anne Revere          1946                    1946  Best Supporting Actress
Faye Dunaway         1977                    1977             Best Actress
Van Heflin           1943                    1943    Best Supporting Actor
Joanne Woodward      1958                    1958             Best Actress
Gary Cooper          1953                    1953               Best Actor
Elizabeth Taylor     1967                    1967             Best Actress
Hilary Swank         2005                    2005             Best Actress
                     2005                    2005             Best Actress
Gwyneth Paltrow      1999                    1999             Best Actress
Jack Albertson       1969                    1969    Best Supporting Actor
Mo'Nique             2010                    2010  Best Supporting Actress
Marcia Gay Harden    2001                    2001  Best Supporting Actress
Maggie Smith         1970                    1970             Best Actress
Rachel Weisz         2006                    2006  Best Supporting Actress
Danny Boyle          2009                    2009            Best Director
Jason Robards        1977                    1977    Best Supporting Actor
James Coburn         1999                    1999    Best Supporting Actor
John Huston          1949                    1949            Best Director

                                                               movie  \
person               year_of_award
Lewis Milestone      1927                        Two Arabian Knights
Frank Lloyd          1930                            The Divine Lady
Lewis Milestone      1931             All Quiet on the Western Front
Norman Taurog        1932                                     Skippy
Frank Borzage        1933                                   Bad Girl
Frank Lloyd          1934                                  Cavalcade
Frank Capra          1935                      It Happened One Night
John Ford            1936                               The Informer
Frank Capra          1937                     Mr. Deeds Goes to Town
Leo McCarey          1938                            The Awful Truth
Frank Capra          1939                 You Can't Take It with You
Victor Fleming       1940                         Gone with the Wind
John Ford            1941                        The Grapes of Wrath
                     1942                    How Green Was My Valley
William Wyler        1943                               Mrs. Miniver
Michael Curtiz       1944                                 Casablanca
Leo McCarey          1945                               Going My Way
Jerome Robbins       1962                            West Side Story
Billy Wilder         1946                           The Lost Weekend
William Wyler        1947                The Best Years of Our Lives
Elia Kazan           1948                      Gentleman's Agreement
John Huston          1949           The Treasure of the Sierra Madre
Joseph L. Mankiewicz 1950                    A Letter to Three Wives
                     1951                              All About Eve
George Stevens       1952                         A Place in the Sun
John Ford            1953                              The Quiet Man
Fred Zinnemann       1954                      From Here to Eternity
Elia Kazan           1955                          On the Waterfront

# Video 5: Renombrando filas y columnas

**Renombrando filas y columnas**
* Para hacerlas mas descriptivas
* Para seguir un estandar
* para evitar blancos y otros caracteres especiales

In [227]:
oscars_byID =pd.read_csv('Oscars-demographics-DFE.csv', encoding='latin-1', index_col=['person','year_of_award'])
oscars_byID.tail()

,,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
person,year_of_award,,,,,,,,,,,,,,,,,,,,,
Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
James Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

In [228]:
# Ejemplo practico de como puedo hacer un rename indicando los elementos especificos y de esta forma voy a poder renombrar tanto filas como columas

In [234]:
idx_rename={'James Coburn':'Jimmy Coburn'}
col_rename={'_unit_id':'unit_ID','_golden':'Golden'}
oscars_byID_renamed = oscars_byID.rename(index=idx_rename, columns=col_rename)
oscars_byID_renamed

                                      unit_ID  Golden _unit_state  \
person               year_of_award
Lewis Milestone      1927           670454353   False   finalized
Frank Lloyd          1930           670454354   False   finalized
Lewis Milestone      1931           670454355   False   finalized
Norman Taurog        1932           670454356   False   finalized
Frank Borzage        1933           670454357   False   finalized
Frank Lloyd          1934           670454358   False   finalized
Frank Capra          1935           670454359   False   finalized
John Ford            1936           670454360   False   finalized
Frank Capra          1937           670454361   False   finalized
Leo McCarey          1938           670454362   False   finalized
Frank Capra          1939           670454363   False   finalized
Victor Fleming       1940           670454364   False   finalized
John Ford            1941           670454365   False   finalized
                     1942           670454366   False   finalized
William Wyler        1943           670454367   False   finalized
Michael Curtiz       1944           670454368   False   finalized
Leo McCarey          1945           670454369   False   finalized
Jerome Robbins       1962           670454370   False   finalized
Billy Wilder         1946           670454371   False   finalized
William Wyler        1947           670454372   False   finalized
Elia Kazan           1948           670454373   False   finalized
John Huston          1949           670454374    True      golden
Joseph L. Mankiewicz 1950           670454375   False   finalized
                     1951           670454376   False   finalized
George Stevens       1952           670454377   False   finalized
John Ford            1953           670454378   False   finalized
Fred Zinnemann       1954           670454379   False   finalized
Elia Kazan           1955           670454380   False   finalized
Delbert Mann         1956           670454381   False   finalized
George Stevens       1957           670454382   False   finalized
...                                       ...     ...         ...
Mo'Nique             2010           670454764    True      golden
Melissa Leo          2011           670454765   False   finalized
Octavia Spencer      2012           670454766   False   finalized
Anne Hathaway        2013           670454767   False   finalized
Lupita Nyong'o       2014           670454768   False   finalized
Billy Wilder         1961           670927629   False   finalized
Ginger Rogers        1941           670939613   False   finalized
Tom Hanks            1994           670944094   False   finalized
Michael Cimino       1979           670944168   False   finalized
Mary Astor           1942           670944316   False   finalized
Angelina Jolie       2000           670944478   False   finalized
Lee Grant            1976           670944543   False   finalized
Anne Revere          1946           670944623   False   finalized
Faye Dunaway         1977           670944674   False   finalized
Van Heflin           1943           670944755   False   finalized
Joanne Woodward      1958           670944822   False   finalized
Gary Cooper          1953           670944835   False   finalized
Elizabeth Taylor     1967           670944920   False   finalized
Hilary Swank         2005           670944948   False   finalized
                     2005           670945043    True      golden
Gwyneth Paltrow      1999           670945693   False   finalized
Jack Albertson       1969           670945790   False   finalized
Mo'Nique             2010           670945834   False   finalized
Marcia Gay Harden    2001           670945895   False   finalized
Maggie Smith         1970           670946199   False   finalized
Rachel Weisz         2006           670946276   False   finalized
Danny Boyle          2009           670946299   False   finalized
Jason Robards        1977           670964912   False   finalized
Jimmy Coburn         1999           670964956   False   finalized
John Huston          1949           670972898   False   finalized

                                    _trusted_judgments _last_judgment_at  \
person               year_of_award
Lewis Milestone      1927                            3      2/10/15 3:45
Frank Lloyd          1930                            3      2/10/15 2:03
Lewis Milestone      1931                            3      2/10/15 2:05
Norman Taurog        1932                            3      2/10/15 2:04
Frank Borzage        1933                            3      2/10/15 1:48
Frank Lloyd          1934                            3      2/10/15 3:50
Frank Capra          1935                            3      2/10/15 2:07
John Ford            1936                            3      2/10/15 1:46
Frank Capra          1937                            3      2/10/15 1:47
Leo McCarey          1938                            3      2/10/15 2:05
Frank Capra          1939                            3      2/10/15 2:04
Victor Fleming       1940                            3      2/10/15 2:10
John Ford            1941                            3      2/10/15 2:12
                     1942                            3      2/10/15 2:02
William Wyler        1943                            3      2/10/15 3:57
Michael Curtiz       1944                            3      2/10/15 2:02
Leo McCarey          1945                            3      2/10/15 2:29
Jerome Robbins       1962                            3      2/10/15 1:55
Billy Wilder         1946                            3      2/10/15 4:02
William Wyler        1947                            3      2/10/15 2:12
Elia Kazan           1948                            3      2/10/15 1:46
John Huston          1949                           82               NaN
Joseph L. Mankiewicz 1950                            3      2/10/15 3:50
                     1951                            3      2/10/15 1:51
George Stevens       1952                            3      2/10/15 2:15
John Ford            1953                            3      2/10/15 2:15
Fred Zinnemann       1954                            3      2/10/15 1:57
Elia Kazan           1955                            3      2/10/15 3:50
Delbert Mann         1956                            3      2/10/15 3:53
George Stevens       1957                            3      2/10/15 3:50
...                                                ...               ...
Mo'Nique             2010                           86               NaN
Melissa Leo          2011                            3      2/10/15 1:56
Octavia Spencer      2012                            3      2/10/15 2:18
Anne Hathaway        2013                            3      2/10/15 2:18
Lupita Nyong'o       2014                            3      2/10/15 2:10
Billy Wilder         1961                            3      2/10/15 2:02
Ginger Rogers        1941                            3      2/10/15 1:53
Tom Hanks            1994                            3      2/10/15 2:18
Michael Cimino       1979                            3      2/10/15 3:55
Mary Astor           1942                            3      2/10/15 2:05
Angelina Jolie       2000                            3      2/10/15 1:49
Lee Grant            1976                            3      2/10/15 2:12
Anne Revere          1946                            3      2/10/15 2:11
Faye Dunaway         1977                            3      2/10/15 2:05
Van Heflin           1943                            3      2/10/15 2:04
Joanne Woodward      1958                            3      2/10/15 4:14
Gary Cooper          1953                            3      2/10/15 2:08
Elizabeth Taylor     1967                            3      2/10/15 3:58
Hilary Swank         2005                            3      2/10/15 2:06
                     2005                           86               NaN
Gwyneth Paltrow      1999                            3      2/10/15 1:49
Jack Albertson       1969                            3      2/10/15 2:08
Mo'Nique             2010                            3      2/10/15 2:07
Marcia Gay Harden    2001                            3      2/10/15 2:13
Maggie Smith         1970                            3      2/10/15 2:03
Rachel Weisz         2006                            3      2/10/15 2:00
Danny Boyle          2009                            3      2/10/15 2:04
Jason Robards        1977                            3      2/10/15 2:03
Jimmy Coburn         1999                            3      2/10/15 2:01
John Huston          1949                            3      2/10/15 2:01

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
Jimmy Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                    birthplace:confidence date_of_birth  \
person               year_of_award
Lewis Milestone      1927                          1.0000   30-Sep-1895
Frank Lloyd          1930                          1.0000    2-Feb-1886
Lewis Milestone      1931                          1.0000   30-Sep-1895
Norman Taurog        1932                          1.0000   23-Feb-1899
Frank Borzage        1933                          1.0000   23-Apr-1894
Frank Lloyd          1934                          1.0000    2-Feb-1886
Frank Capra          1935                          1.0000   18-May-1897
John Ford            1936                          1.0000    1-Feb-1894
Frank Capra          1937                          1.0000   18-May-1897
Leo McCarey          1938                          1.0000    3-Oct-1898
Frank Capra          1939                          1.0000   18-May-1897
Victor Fleming       1940                          1.0000   23-Feb-1883
John Ford            1941                          1.0000    1-Feb-1894
                     1942                          1.0000    1-Feb-1894
William Wyler        1943                          1.0000    1-Jul-1902
Michael Curtiz       1944                          1.0000   24-Dec-1886
Leo McCarey          1945                          1.0000    3-Oct-1898
Jerome Robbins       1962                          1.0000     11-Oct-18
Billy Wilder         1946                          0.6667     22-Jun-06
William Wyler        1947                          1.0000    1-Jul-1902
Elia Kazan           1948                          1.0000      7-Sep-09
John Huston          1949                          1.0000      5-Aug-06
Joseph L. Mankiewicz 1950                          1.0000     11-Feb-09
                     1951                          1.0000     11-Feb-09
George Stevens       1952                          1.0000     18-Dec-04
John Ford            1953                          1.0000    1-Feb-1894
Fred Zinnemann       1954                          1.0000     29-Apr-07
Elia Kazan           1955                          1.0000      7-Sep-09
Delbert Mann         1956                          1.0000     30-Jan-20
George Stevens       1957                          1.0000     18-Dec-04
...                                                   ...           ...
Mo'Nique             2010                          1.0000     11-Dec-67
Melissa Leo          2011                          1.0000     14-Sep-60
Octavia Spencer      2012                          1.0000     25-May-72
Anne Hathaway        2013                          1.0000     12-Nov-82
Lupita Nyong'o       2014                          1.0000      1-Mar-83
Billy Wilder         1961                          1.0000     22-Jun-06
Ginger Rogers        1941                          1.0000     16-Jul-11
Tom Hanks            1994                          1.0000      9-Jul-56
Michael Cimino       1979                          1.0000      3-Feb-39
Mary Astor           1942                          1.0000      3-May-06
Angelina Jolie       2000                          1.0000      4-Jun-75
Lee Grant            1976                          1.0000     31-Oct-27
Anne Revere          1946                          1.0000   25-Jun-1903
Faye Dunaway         1977                          1.0000     14-Jan-41
Van Heflin           1943                          1.0000     13-Dec-10
Joanne Woodward      1958                          1.0000     27-Feb-30
Gary Cooper          1953                          1.0000    7-May-1901
Elizabeth Taylor     1967                          1.0000     27-Feb-32
Hilary Swank         2005                          1.0000     30-Jul-74
                     2005                          1.0000     30-Jul-74
Gwyneth Paltrow      1999                          1.0000     27-Sep-72
Jack Albertson       1969                          1.0000     16-Jun-07
Mo'Nique             2010                          1.0000     11-Dec-67
Marcia Gay Harden    2001                          1.0000     14-Aug-59
Maggie Smith         1970                          1.0000     28-Dec-34
Rachel Weisz         2006                          1.0000      7-Mar-71
Danny Boyle          2009                          1.0000     20-Oct-56
Jason Robards        1977                          1.0000     26-Jul-22
Jimmy Coburn         1999                          1.0000     31-Aug-28
John Huston          1949                          1.0000      5-Aug-06

                                    date_of_birth:confidence race_ethnicity  \
person               year_of_award
Lewis Milestone      1927                             1.0000          White
Frank Lloyd          1930                             1.0000          White
Lewis Milestone      1931                             1.0000          White
Norman Taurog        1932                             1.0000          White
Frank Borzage        1933                             1.0000          White
Frank Lloyd          1934                             1.0000          White
Frank Capra          1935                             1.0000          White
John Ford            1936                             1.0000          White
Frank Capra          1937                             1.0000          White
Leo McCarey          1938                             1.0000          White
Frank Capra          1939                             1.0000          White
Victor Fleming       1940                             1.0000          White
John Ford            1941                             1.0000          White
                     1942                             1.0000          White
William Wyler        1943                             1.0000          White
Michael Curtiz       1944                             1.0000          White
Leo McCarey          1945                             1.0000          White
Jerome Robbins       1962                             1.0000          White
Billy Wilder         1946                             1.0000          White
William Wyler        1947                             1.0000          White
Elia Kazan           1948                             1.0000          White
John Huston          1949                             1.0000          White
Joseph L. Mankiewicz 1950                             1.0000          White
                     1951                             1.0000          White
George Stevens       1952                             1.0000          White
John Ford            1953                             1.0000          White
Fred Zinnemann       1954                             1.0000          White
Elia Kazan           1955                             1.0000          White

In [235]:
oscars_byID_renamed.tail()

,,unit_ID,Golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
person,year_of_award,,,,,,,,,,,,,,,,,,,,,
Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
Jimmy Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

In [247]:
# Consulta: ¿Si indico como parametro otro año? oscars_byID.loc[['James Coburn','2000'],:] y trae lo mismos datos
oscars_byID.loc[['James Coburn','1999'],:]

                             _unit_id  _golden _unit_state  \
person       year_of_award
James Coburn 1999           670454588     True      golden
             1999           670964956    False   finalized

                            _trusted_judgments _last_judgment_at  birthplace  \
person       year_of_award
James Coburn 1999                           62               NaN  Laurel, Ne
             1999                            3      2/10/15 2:01  Laurel, Ne

                            birthplace:confidence date_of_birth  \
person       year_of_award
James Coburn 1999                             1.0     31-Aug-28
             1999                             1.0     31-Aug-28

                            date_of_birth:confidence race_ethnicity  \
person       year_of_award
James Coburn 1999                                1.0          White
             1999                                1.0          White

                                  ...          year_of_award:confidence  \
person       year_of_award        ...
James Coburn 1999                 ...                               1.0
             1999                 ...                               1.0

                                            award  \
person       year_of_award
James Coburn 1999           Best Supporting Actor
             1999           Best Supporting Actor

                                                               biourl  \
person       year_of_award
James Coburn 1999           http://www.nndb.com/people/764/000022698/
             1999           http://www.nndb.com/people/764/000022698/

                           birthplace_gold  date_of_birth_gold       movie  \
person       year_of_award
James Coburn 1999                      NaN                 NaN  Affliction
             1999                      NaN                 NaN  Affliction

                           race_ethnicity_gold religion_gold  \
person       year_of_award
James Coburn 1999                          NaN            Na
             1999                          NaN           NaN

                           sexual_orientation_gold year_of_award_gold
person       year_of_award
James Coburn 1999                              NaN                NaN
             1999                              NaN                NaN

[2 rows x 25 columns]

In [248]:
# Podemos obtener indices y columas desde el business dataframe
oscars_columns = oscars_byID.columns
oscars_columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'race_ethnicity_gold', 'religion_gold',
       'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [249]:
print(oscars_byID.columns)

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'race_ethnicity_gold', 'religion_gold',
       'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [251]:
# ahora las pasamos a una lista de columnas
columns_list = oscars_columns.tolist()
columns_list

['_unit_id',
 '_golden',
 '_unit_state',
 '_trusted_judgments',
 '_last_judgment_at',
 'birthplace',
 'birthplace:confidence',
 'date_of_birth',
 'date_of_birth:confidence',
 'race_ethnicity',
 'race_ethnicity:confidence',
 'religion',
 'religion:confidence',
 'sexual_orientation',
 'sexual_orientation:confidence',
 'year_of_award:confidence',
 'award',
 'biourl',
 'birthplace_gold',
 'date_of_birth_gold',
 'movie',
 'race_ethnicity_gold',
 'religion_gold',
 'sexual_orientation_gold',
 'year_of_award_gold']

In [252]:
# renombro uno o mas elementos de la lista
# en este caso, al elemento 0 de la lista '_unit_id' lo voy a renombrar a 'unitID'
columns_list[0]='unitID'

In [253]:
columns_list

['unitID',
 '_golden',
 '_unit_state',
 '_trusted_judgments',
 '_last_judgment_at',
 'birthplace',
 'birthplace:confidence',
 'date_of_birth',
 'date_of_birth:confidence',
 'race_ethnicity',
 'race_ethnicity:confidence',
 'religion',
 'religion:confidence',
 'sexual_orientation',
 'sexual_orientation:confidence',
 'year_of_award:confidence',
 'award',
 'biourl',
 'birthplace_gold',
 'date_of_birth_gold',
 'movie',
 'race_ethnicity_gold',
 'religion_gold',
 'sexual_orientation_gold',
 'year_of_award_gold']

In [254]:
# Y finalmente lo asigno nuevamente al Data Frame
oscars_byID.columns=columns_list
oscars_byID

                                       unitID  _golden _unit_state  \
person               year_of_award
Lewis Milestone      1927           670454353    False   finalized
Frank Lloyd          1930           670454354    False   finalized
Lewis Milestone      1931           670454355    False   finalized
Norman Taurog        1932           670454356    False   finalized
Frank Borzage        1933           670454357    False   finalized
Frank Lloyd          1934           670454358    False   finalized
Frank Capra          1935           670454359    False   finalized
John Ford            1936           670454360    False   finalized
Frank Capra          1937           670454361    False   finalized
Leo McCarey          1938           670454362    False   finalized
Frank Capra          1939           670454363    False   finalized
Victor Fleming       1940           670454364    False   finalized
John Ford            1941           670454365    False   finalized
                     1942           670454366    False   finalized
William Wyler        1943           670454367    False   finalized
Michael Curtiz       1944           670454368    False   finalized
Leo McCarey          1945           670454369    False   finalized
Jerome Robbins       1962           670454370    False   finalized
Billy Wilder         1946           670454371    False   finalized
William Wyler        1947           670454372    False   finalized
Elia Kazan           1948           670454373    False   finalized
John Huston          1949           670454374     True      golden
Joseph L. Mankiewicz 1950           670454375    False   finalized
                     1951           670454376    False   finalized
George Stevens       1952           670454377    False   finalized
John Ford            1953           670454378    False   finalized
Fred Zinnemann       1954           670454379    False   finalized
Elia Kazan           1955           670454380    False   finalized
Delbert Mann         1956           670454381    False   finalized
George Stevens       1957           670454382    False   finalized
...                                       ...      ...         ...
Mo'Nique             2010           670454764     True      golden
Melissa Leo          2011           670454765    False   finalized
Octavia Spencer      2012           670454766    False   finalized
Anne Hathaway        2013           670454767    False   finalized
Lupita Nyong'o       2014           670454768    False   finalized
Billy Wilder         1961           670927629    False   finalized
Ginger Rogers        1941           670939613    False   finalized
Tom Hanks            1994           670944094    False   finalized
Michael Cimino       1979           670944168    False   finalized
Mary Astor           1942           670944316    False   finalized
Angelina Jolie       2000           670944478    False   finalized
Lee Grant            1976           670944543    False   finalized
Anne Revere          1946           670944623    False   finalized
Faye Dunaway         1977           670944674    False   finalized
Van Heflin           1943           670944755    False   finalized
Joanne Woodward      1958           670944822    False   finalized
Gary Cooper          1953           670944835    False   finalized
Elizabeth Taylor     1967           670944920    False   finalized
Hilary Swank         2005           670944948    False   finalized
                     2005           670945043     True      golden
Gwyneth Paltrow      1999           670945693    False   finalized
Jack Albertson       1969           670945790    False   finalized
Mo'Nique             2010           670945834    False   finalized
Marcia Gay Harden    2001           670945895    False   finalized
Maggie Smith         1970           670946199    False   finalized
Rachel Weisz         2006           670946276    False   finalized
Danny Boyle          2009           670946299    False   finalized
Jason Robards        1977           670964912    False   finalized
James Coburn         1999           670964956    False   finalized
John Huston          1949           670972898    False   finalized

                                    _trusted_judgments _last_judgment_at  \
person               year_of_award
Lewis Milestone      1927                            3      2/10/15 3:45
Frank Lloyd          1930                            3      2/10/15 2:03
Lewis Milestone      1931                            3      2/10/15 2:05
Norman Taurog        1932                            3      2/10/15 2:04
Frank Borzage        1933                            3      2/10/15 1:48
Frank Lloyd          1934                            3      2/10/15 3:50
Frank Capra          1935                            3      2/10/15 2:07
John Ford            1936                            3      2/10/15 1:46
Frank Capra          1937                            3      2/10/15 1:47
Leo McCarey          1938                            3      2/10/15 2:05
Frank Capra          1939                            3      2/10/15 2:04
Victor Fleming       1940                            3      2/10/15 2:10
John Ford            1941                            3      2/10/15 2:12
                     1942                            3      2/10/15 2:02
William Wyler        1943                            3      2/10/15 3:57
Michael Curtiz       1944                            3      2/10/15 2:02
Leo McCarey          1945                            3      2/10/15 2:29
Jerome Robbins       1962                            3      2/10/15 1:55
Billy Wilder         1946                            3      2/10/15 4:02
William Wyler        1947                            3      2/10/15 2:12
Elia Kazan           1948                            3      2/10/15 1:46
John Huston          1949                           82               NaN
Joseph L. Mankiewicz 1950                            3      2/10/15 3:50
                     1951                            3      2/10/15 1:51
George Stevens       1952                            3      2/10/15 2:15
John Ford            1953                            3      2/10/15 2:15
Fred Zinnemann       1954                            3      2/10/15 1:57
Elia Kazan           1955                            3      2/10/15 3:50
Delbert Mann         1956                            3      2/10/15 3:53
George Stevens       1957                            3      2/10/15 3:50
...                                                ...               ...
Mo'Nique             2010                           86               NaN
Melissa Leo          2011                            3      2/10/15 1:56
Octavia Spencer      2012                            3      2/10/15 2:18
Anne Hathaway        2013                            3      2/10/15 2:18
Lupita Nyong'o       2014                            3      2/10/15 2:10
Billy Wilder         1961                            3      2/10/15 2:02
Ginger Rogers        1941                            3      2/10/15 1:53
Tom Hanks            1994                            3      2/10/15 2:18
Michael Cimino       1979                            3      2/10/15 3:55
Mary Astor           1942                            3      2/10/15 2:05
Angelina Jolie       2000                            3      2/10/15 1:49
Lee Grant            1976                            3      2/10/15 2:12
Anne Revere          1946                            3      2/10/15 2:11
Faye Dunaway         1977                            3      2/10/15 2:05
Van Heflin           1943                            3      2/10/15 2:04
Joanne Woodward      1958                            3      2/10/15 4:14
Gary Cooper          1953                            3      2/10/15 2:08
Elizabeth Taylor     1967                            3      2/10/15 3:58
Hilary Swank         2005                            3      2/10/15 2:06
                     2005                           86               NaN
Gwyneth Paltrow      1999                            3      2/10/15 1:49
Jack Albertson       1969                            3      2/10/15 2:08
Mo'Nique             2010                            3      2/10/15 2:07
Marcia Gay Harden    2001                            3      2/10/15 2:13
Maggie Smith         1970                            3      2/10/15 2:03
Rachel Weisz         2006                            3      2/10/15 2:00
Danny Boyle          2009                            3      2/10/15 2:04
Jason Robards        1977                            3      2/10/15 2:03
James Coburn         1999                            3      2/10/15 2:01
John Huston          1949                            3      2/10/15 2:01

                                                             birthplace  \
person               year_of_award
Lewis Milestone      1927                             Chisinau, Moldova
Frank Lloyd          1930                             Glasgow, Scotland
Lewis Milestone      1931                             Chisinau, Moldova
Norman Taurog        1932                                   Chicago, Il
Frank Borzage        1933                            Salt Lake City, Ut
Frank Lloyd          1934                             Glasgow, Scotland
Frank Capra          1935                     Bisacquino, Sicily, Italy
John Ford            1936                            Cape Elizabeth, Me
Frank Capra          1937                     Bisacquino, Sicily, Italy
Leo McCarey          1938                               Los Angeles, Ca
Frank Capra          1939                     Bisacquino, Sicily, Italy
Victor Fleming       1940                                  Pasadena, Ca
John Ford            1941                            Cape Elizabeth, Me
                     1942                            Cape Elizabeth, Me
William Wyler        1943           Mulhouse, Haut-Rhin, Alsace, France
Michael Curtiz       1944                             Budapest, Hungary
Leo McCarey          1945                               Los Angeles, Ca
Jerome Robbins       1962                                 New York City
Billy Wilder         1946                       Sucha, Galicia, Austria
William Wyler        1947           Mulhouse, Haut-Rhin, Alsace, France
Elia Kazan           1948                              Istanbul, Turkey
John Huston          1949                                    Nevada, Mo
Joseph L. Mankiewicz 1950                              Wilkes-Barre, Pa
                     1951                              Wilkes-Barre, Pa
George Stevens       1952                                   Oakland, Ca
John Ford            1953                            Cape Elizabeth, Me
Fred Zinnemann       1954                               Vienna, Austria
Elia Kazan           1955                              Istanbul, Turkey
Delbert Mann         1956                                  Lawrence, Ks
George Stevens       1957                                   Oakland, Ca
...                                                                 ...
Mo'Nique             2010                                  Woodlawn, Md
Melissa Leo          2011                                 New York City
Octavia Spencer      2012                                Montgomery, Al
Anne Hathaway        2013                                  Brooklyn, Ny
Lupita Nyong'o       2014                           Mexico City, Mexico
Billy Wilder         1961                       Sucha, Galicia, Austria
Ginger Rogers        1941                              Independence, Mo
Tom Hanks            1994                                   Concord, Ca
Michael Cimino       1979                                 New York City
Mary Astor           1942                                    Quincy, Il
Angelina Jolie       2000                               Los Angeles, Ca
Lee Grant            1976                                 New York City
Anne Revere          1946                                 New York City
Faye Dunaway         1977                                    Bascom, Fl
Van Heflin           1943                                   Walters, Ok
Joanne Woodward      1958                               Thomasville, Ga
Gary Cooper          1953                                    Helena, Mt
Elizabeth Taylor     1967                               London, England
Hilary Swank         2005                                   Lincoln, Ne
                     2005                                   Lincoln, Ne
Gwyneth Paltrow      1999                               Los Angeles, Ca
Jack Albertson       1969                                    Malden, Ma
Mo'Nique             2010                                  Woodlawn, Md
Marcia Gay Harden    2001                                  La Jolla, Ca
Maggie Smith         1970                        Ilford, Essex, England
Rachel Weisz         2006                               London, England
Danny Boyle          2009                           Manchester, England
Jason Robards        1977                                   Chicago, Il
James Coburn         1999                                    Laurel, Ne
John Huston          1949                                    Nevada, Mo

                                    birthplace:confidence date_of_birth  \
person               year_of_award
Lewis Milestone      1927                          1.0000   30-Sep-1895
Frank Lloyd          1930                          1.0000    2-Feb-1886
Lewis Milestone      1931                          1.0000   30-Sep-1895
Norman Taurog        1932                          1.0000   23-Feb-1899
Frank Borzage        1933                          1.0000   23-Apr-1894
Frank Lloyd          1934                          1.0000    2-Feb-1886
Frank Capra          1935                          1.0000   18-May-1897
John Ford            1936                          1.0000    1-Feb-1894
Frank Capra          1937                          1.0000   18-May-1897
Leo McCarey          1938                          1.0000    3-Oct-1898
Frank Capra          1939                          1.0000   18-May-1897
Victor Fleming       1940                          1.0000   23-Feb-1883
John Ford            1941                          1.0000    1-Feb-1894
                     1942                          1.0000    1-Feb-1894
William Wyler        1943                          1.0000    1-Jul-1902
Michael Curtiz       1944                          1.0000   24-Dec-1886
Leo McCarey          1945                          1.0000    3-Oct-1898
Jerome Robbins       1962                          1.0000     11-Oct-18
Billy Wilder         1946                          0.6667     22-Jun-06
William Wyler        1947                          1.0000    1-Jul-1902
Elia Kazan           1948                          1.0000      7-Sep-09
John Huston          1949                          1.0000      5-Aug-06
Joseph L. Mankiewicz 1950                          1.0000     11-Feb-09
                     1951                          1.0000     11-Feb-09
George Stevens       1952                          1.0000     18-Dec-04
John Ford            1953                          1.0000    1-Feb-1894
Fred Zinnemann       1954                          1.0000     29-Apr-07
Elia Kazan           1955                          1.0000      7-Sep-09
Delbert Mann         1956                          1.0000     30-Jan-20
George Stevens       1957                          1.0000     18-Dec-04
...                                                   ...           ...
Mo'Nique             2010                          1.0000     11-Dec-67
Melissa Leo          2011                          1.0000     14-Sep-60
Octavia Spencer      2012                          1.0000     25-May-72
Anne Hathaway        2013                          1.0000     12-Nov-82
Lupita Nyong'o       2014                          1.0000      1-Mar-83
Billy Wilder         1961                          1.0000     22-Jun-06
Ginger Rogers        1941                          1.0000     16-Jul-11
Tom Hanks            1994                          1.0000      9-Jul-56
Michael Cimino       1979                          1.0000      3-Feb-39
Mary Astor           1942                          1.0000      3-May-06
Angelina Jolie       2000                          1.0000      4-Jun-75
Lee Grant            1976                          1.0000     31-Oct-27
Anne Revere          1946                          1.0000   25-Jun-1903
Faye Dunaway         1977                          1.0000     14-Jan-41
Van Heflin           1943                          1.0000     13-Dec-10
Joanne Woodward      1958                          1.0000     27-Feb-30
Gary Cooper          1953                          1.0000    7-May-1901
Elizabeth Taylor     1967                          1.0000     27-Feb-32
Hilary Swank         2005                          1.0000     30-Jul-74
                     2005                          1.0000     30-Jul-74
Gwyneth Paltrow      1999                          1.0000     27-Sep-72
Jack Albertson       1969                          1.0000     16-Jun-07
Mo'Nique             2010                          1.0000     11-Dec-67
Marcia Gay Harden    2001                          1.0000     14-Aug-59
Maggie Smith         1970                          1.0000     28-Dec-34
Rachel Weisz         2006                          1.0000      7-Mar-71
Danny Boyle          2009                          1.0000     20-Oct-56
Jason Robards        1977                          1.0000     26-Jul-22
James Coburn         1999                          1.0000     31-Aug-28
John Huston          1949                          1.0000      5-Aug-06

                                    date_of_birth:confidence race_ethnicity  \
person               year_of_award
Lewis Milestone      1927                             1.0000          White
Frank Lloyd          1930                             1.0000          White
Lewis Milestone      1931                             1.0000          White
Norman Taurog        1932                             1.0000          White
Frank Borzage        1933                             1.0000          White
Frank Lloyd          1934                             1.0000          White
Frank Capra          1935                             1.0000          White
John Ford            1936                             1.0000          White
Frank Capra          1937                             1.0000          White
Leo McCarey          1938                             1.0000          White
Frank Capra          1939                             1.0000          White
Victor Fleming       1940                             1.0000          White
John Ford            1941                             1.0000          White
                     1942                             1.0000          White
William Wyler        1943                             1.0000          White
Michael Curtiz       1944                             1.0000          White
Leo McCarey          1945                             1.0000          White
Jerome Robbins       1962                             1.0000          White
Billy Wilder         1946                             1.0000          White
William Wyler        1947                             1.0000          White
Elia Kazan           1948                             1.0000          White
John Huston          1949                             1.0000          White
Joseph L. Mankiewicz 1950                             1.0000          White
                     1951                             1.0000          White
George Stevens       1952                             1.0000          White
John Ford            1953                             1.0000          White
Fred Zinnemann       1954                             1.0000          White

# Video 6 Pandas: Creacion y borrado de columnas en un Dataframe

In [270]:
# Si quisieramos facilmente crear UNA NUEVA COLUMNA asignando todos los valores en cero
oscars_short = pd.read_csv('Oscars-demographics-DFE.csv', encoding ='latin-1',\
                          usecols=['birthplace','date_of_birth','race_ethnicity','religion','sexual_orientation','year_of_award',\
                                  'award','movie','person'])
oscars_short.tail()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [273]:
# Creo la columna 'last_ten_years' con valores cero
oscars_short['last_ten_years']=0
oscars_short

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person,last_ten_years
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone,0
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd,0
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone,0
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog,0
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage,0
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd,0
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra,0
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford,0
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra,0
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey,0
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra,0
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming,0
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford,0
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford,0
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler,0
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz,0
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey,0
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins,0
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder,0
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler,0
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan,0
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston,0
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz,0
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz,0
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens,0
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford,0
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann,0
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan,0
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann,0
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens,0
...,...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique,0
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo,0
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer,0
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway,0
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o,0
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder,0
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers,0
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks,0
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino,0
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor,0
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie,0
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant,0
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere,0
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway,0
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin,0
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward,0
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper,0
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor,0
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank,0
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank,0
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow,0
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson,0
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique,0
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden,0
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith,0
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz,0
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle,0
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards,0
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn,0
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston,0

In [277]:
# Otra opcion puede ser asignarle a la columna nueva 'last_ten_years' un valor calculado por comparacion
oscars_short['last_ten_years'] = oscars_short['year_of_award']>2009

In [262]:
oscars_short

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person,last_ten_years
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone,False
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd,False
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone,False
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog,False
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage,False
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd,False
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra,False
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford,False
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra,False
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey,False
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra,False
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming,False
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford,False
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford,False
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler,False
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz,False
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey,False
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins,False
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder,False
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler,False
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan,False
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston,False
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz,False
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz,False
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens,False
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford,False
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann,False
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan,False
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann,False
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens,False
...,...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique,False
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo,False
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer,False
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway,False
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o,False
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder,False
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers,False
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks,False
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino,False
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor,False
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie,False
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant,False
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere,False
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway,False
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin,False
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward,False
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper,False
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor,False
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank,False
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank,False
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow,False
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson,False
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique,False
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden,False
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith,False
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz,False
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle,False
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards,False
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn,False
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston,False

In [278]:
# verifico haciendo un values_count()
oscars_short['last_ten_years'].value_counts()

False    417
True      24
Name: last_ten_years, dtype: int64

In [281]:
# Si quiero eliminar la columna que creamos, solo hacemos un drop
oscars_short.drop(columns='last_ten_years', inplace=True)

In [267]:
oscars_short

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [279]:
# Si quisieramos agregar la columna en un lugar especifico del data frame (por ejemplo entre la fecha de nacimeint oy la raza del grupo etnico)

# 1) calculamos la posicion con get_loc()
date_of_birth_position=oscars_short.columns.get_loc('date_of_birth')+1
date_of_birth_position

2

In [282]:
# ahora que tenemos la posicion de la nueva columna, hacemos un insert y le vamos a indicar que la posicion es la que calculamos (date of birth +1) y le ponemos el nombre
#y le indicamos el valor que puede tomar

oscars_short.insert(loc=date_of_birth_position, column='last_ten_years', value=(oscars_short['year_of_award']>2009))
oscars_short

,birthplace,date_of_birth,last_ten_years,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,False,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,False,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,False,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,False,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,False,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,False,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,False,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,False,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,False,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,False,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,False,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,False,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,False,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,False,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,False,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,False,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,False,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,False,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,False,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,False,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,False,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,False,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,False,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,False,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,False,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,False,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,False,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,False,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,False,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,False,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,True,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,True,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,True,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,True,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,True,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
416,"Sucha, Galicia, Austria",22-Jun-06,False,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
417,"Independence, Mo",16-Jul-11,False,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers
418,"Concord, Ca",9-Jul-56,False,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks
419,New York City,3-Feb-39,False,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
420,"Quincy, Il",3-May-06,False,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor
421,"Los Angeles, Ca",4-Jun-75,False,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,False,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,False,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,False,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,False,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,False,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,False,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,False,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,False,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,False,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,False,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,False,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,True,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,False,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,False,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,False,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,False,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,False,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,False,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,False,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [283]:
# verifico haciendo un values_count()
oscars_short['last_ten_years'].value_counts()

False    417
True      24
Name: last_ten_years, dtype: int64

In [284]:
# la otra opcion que tenemos para borrar la columna es con un del
del oscars_short['last_ten_years']

In [285]:
oscars_short

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",23-Feb-1883,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",24-Dec-1886,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,11-Oct-18,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1-Jul-1902,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",11-Feb-09,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",18-Dec-04,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",29-Apr-07,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",7-Sep-09,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",30-Jan-20,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",18-Dec-04,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
411,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,14-Sep-60,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",25-May-72,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",12-Nov-82,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1-Mar-83,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
416,"Sucha, Galicia, Austria",22-Jun-06,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
417,"Independence, Mo",16-Jul-11,White,Christian Science,Straight,1941,Best Actress,Kitty Foyle,Ginger Rogers
418,"Concord, Ca",9-Jul-56,White,Born-Again Christian,Straight,1994,Best Actor,Philadelphia,Tom Hanks
419,New York City,3-Feb-39,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
420,"Quincy, Il",3-May-06,White,Roman Catholic,Straight,1942,Best Supporting Actress,The Great Lie,Mary Astor
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

#  Video 7 Pandas: Operaciones sobre Dataframe

**Ahora revisamermos otros metodos que aplican a DATAFRAMES, como seleccionar multiples files, como encadenar multiples metodos, etc**

In [320]:
# Similar a lo que hicimos cuando seleccionamos una columna, pero en lugar de proveer un nombre de columnas, pasaremos una lista  de columnas
oscars_basics=oscars_short[['person','movie','award','year_of_award']]
oscars_basics

,person,movie,award,year_of_award
0,Lewis Milestone,Two Arabian Knights,Best Director,1927
1,Frank Lloyd,The Divine Lady,Best Director,1930
2,Lewis Milestone,All Quiet on the Western Front,Best Director,1931
3,Norman Taurog,Skippy,Best Director,1932
4,Frank Borzage,Bad Girl,Best Director,1933
5,Frank Lloyd,Cavalcade,Best Director,1934
6,Frank Capra,It Happened One Night,Best Director,1935
7,John Ford,The Informer,Best Director,1936
8,Frank Capra,Mr. Deeds Goes to Town,Best Director,1937
9,Leo McCarey,The Awful Truth,Best Director,1938
10,Frank Capra,You Can't Take It with You,Best Director,1939
11,Victor Fleming,Gone with the Wind,Best Director,1940
12,John Ford,The Grapes of Wrath,Best Director,1941
13,John Ford,How Green Was My Valley,Best Director,1942
14,William Wyler,Mrs. Miniver,Best Director,1943
15,Michael Curtiz,Casablanca,Best Director,1944
16,Leo McCarey,Going My Way,Best Director,1945
17,Jerome Robbins,West Side Story,Best Director,1962
18,Billy Wilder,The Lost Weekend,Best Director,1946
19,William Wyler,The Best Years of Our Lives,Best Director,1947
20,Elia Kazan,Gentleman's Agreement,Best Director,1948
21,John Huston,The Treasure of the Sierra Madre,Best Director,1949
22,Joseph L. Mankiewicz,A Letter to Three Wives,Best Director,1950
23,Joseph L. Mankiewicz,All About Eve,Best Director,1951
24,George Stevens,A Place in the Sun,Best Director,1952
25,John Ford,The Quiet Man,Best Director,1953
26,Fred Zinnemann,From Here to Eternity,Best Director,1954
27,Elia Kazan,On the Waterfront,Best Director,1955
28,Delbert Mann,Marty,Best Director,1956
29,George Stevens,Giant,Best Director,1957
...,...,...,...,...
411,Mo'Nique,Precious,Best Supporting Actress,2010
412,Melissa Leo,The Fighter,Best Supporting Actress,2011
413,Octavia Spencer,The Help,Best Supporting Actress,2012
414,Anne Hathaway,Les MisÌ©rables,Best Supporting Actress,2013
415,Lupita Nyong'o,12 Years a Slave,Best Supporting Actress,2014
416,Billy Wilder,The Apartment,Best Director,1961
417,Ginger Rogers,Kitty Foyle,Best Actress,1941
418,Tom Hanks,Philadelphia,Best Actor,1994
419,Michael Cimino,The Deer Hunter,Best Director,1979
420,Mary Astor,The Great Lie,Best Supporting Actress,1942
421,Angelina Jolie,"Girl, Interrupted",Best Supporting Actress,2000
422,Lee Grant,Shampoo,Best Supporting Actress,1976
423,Anne Revere,National Velvet,Best Supporting Actress,1946
424,Faye Dunaway,Network,Best Actress,1977
425,Van Heflin,Johnny Eager,Best Supporting Actor,1943
426,Joanne Woodward,The Three Faces of Eve,Best Actress,1958
427,Gary Cooper,High Noon,Best Actor,1953
428,Elizabeth Taylor,Who's Afraid of Virginia Woolf?,Best Actress,1967
429,Hilary Swank,Million Dollar Baby,Best Actress,2005
430,Hilary Swank,Million Dollar Baby,Best Actress,2005
431,Gwyneth Paltrow,Shakespeare in Love,Best Actress,1999
432,Jack Albertson,The Subject Was Roses,Best Supporting Actor,1969
433,Mo'Nique,Precious,Best Supporting Actress,2010
434,Marcia Gay Harden,Pollock,Best Supporting Actress,2001
435,Maggie Smith,The Prime of Miss Jean Brodie,Best Actress,1970
436,Rachel Weisz,The Constant Gardener,Best Supporting Actress,2006
437,Danny Boyle,Slumdog Millionaire,Best Director,2009
438,Jason Robards,All the President's Men,Best Supporting Actor,1977
439,James Coburn,Affliction,Best Supporting Actor,1999
440,John Huston,The Treasure of the Sierra Madre,Best Director,1949

In [321]:
# Podemos seleccionar columnas con metodos
oscars_short.dtypes.value_counts()

object            7
int64             1
datetime64[ns]    1
dtype: int64

In [323]:
oscars_short.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 9 columns):
birthplace            441 non-null object
date_of_birth         440 non-null datetime64[ns]
race_ethnicity        441 non-null object
religion              441 non-null object
sexual_orientation    441 non-null object
year_of_award         441 non-null int64
award                 441 non-null object
movie                 441 non-null object
person                441 non-null object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 31.1+ KB

In [324]:
# convertimos una columna en formato fecha, asignandole el resultado de transformar en formato fecha oscars_short la columna
# 'date_of_birth'
oscars_short.loc[:,'date_of_birth']=pd.to_datetime(oscars_short['date_of_birth'],errors='coerce')

In [325]:
## del oscars_short['date_of_bith']
## le borre la columna porque al hacer oscars_short.loc habia creado 'date_of_both' en lugar

In [326]:
# Repetimos la operacion para ver los tipos de datos que tiene cada columna y 'date_of_birth' cambio a tipo 
oscars_short.dtypes.value_counts()

object            7
int64             1
datetime64[ns]    1
dtype: int64

In [327]:
oscars_short['date_of_birth'].to_frame().info() 
#oscars_demographics['person'].to_frame().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 1 columns):
date_of_birth    440 non-null datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 3.5 KB

In [330]:
#Se casteo a '<M8[ns]'
oscars_short['date_of_birth'].dtype

dtype('<M8[ns]')

In [315]:
oscars_short.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 10 columns):
birthplace            441 non-null object
date_of_birth         440 non-null datetime64[ns]
race_ethnicity        441 non-null object
religion              441 non-null object
sexual_orientation    441 non-null object
year_of_award         441 non-null int64
award                 441 non-null object
movie                 441 non-null object
person                441 non-null object
date_of_bith          440 non-null datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(7)
memory usage: 34.5+ KB

**Tambien se pueden seleccionar columnas con el mismo formato**

In [331]:
# Usamos el metodo select_dtypes como parametro, lo que hace es incluir el tipo de datos que estas buscando

In [332]:
oscars_short.select_dtypes(include=['int64']).head()

   year_of_award
0           1927
1           1930
2           1931
3           1932
4           1933

In [333]:
oscars_short.select_dtypes(include=['<M8[ns]']).head()

  date_of_birth
0    1895-09-30
1    1886-02-02
2    1895-09-30
3    1899-02-23
4    1894-04-23

** Si quisieramos seleccionar todas las columnas con formato numerico, ponemos 'number'

In [335]:
#Si tuvieramos un float, tambien lo incluiria. EN este caso el dataframe solo tiene 1 sola serie con tipo de numero number
oscars_short.select_dtypes(include=['number']).head()

   year_of_award
0           1927
1           1930
2           1931
3           1932
4           1933

**Tambien podemos seleccionar columnas, filtrando por el contenido del nombre de la columa**

In [336]:
oscars_short.filter(like='birth').head()

           birthplace date_of_birth
0   Chisinau, Moldova    1895-09-30
1   Glasgow, Scotland    1886-02-02
2   Chisinau, Moldova    1895-09-30
3         Chicago, Il    1899-02-23
4  Salt Lake City, Ut    1894-04-23

In [339]:
# El filtro tambien se puede hacer por expresiones regulares
# por ejemplo podemos buscar todas las columnas que contengas un '_' en su nombre
oscars_short.filter(regex='\_').head()

  date_of_birth race_ethnicity sexual_orientation  year_of_award
0    1895-09-30          White           Straight           1927
1    1886-02-02          White           Straight           1930
2    1895-09-30          White           Straight           1931
3    1899-02-23          White           Straight           1932
4    1894-04-23          White           Straight           1933

**Tambien podemos usar el nombre de la lista o de la columna**

In [340]:
oscars_short.filter(items=['person']).head()

            person
0  Lewis Milestone
1      Frank Lloyd
2  Lewis Milestone
3    Norman Taurog
4    Frank Borzage

In [343]:
print(oscars_short['person'].head())

0    Lewis Milestone
1        Frank Lloyd
2    Lewis Milestone
3      Norman Taurog
4      Frank Borzage
Name: person, dtype: object

## Ordenar columnas

In [344]:
oscars_short.columns

Index(['birthplace', 'date_of_birth', 'race_ethnicity', 'religion',
       'sexual_orientation', 'year_of_award', 'award', 'movie', 'person'],
      dtype='object')

In [345]:
# Imaginemos que queremos tener en lnombde la persona al principio
new_col_order=['person','birthplace', 'date_of_birth', 'race_ethnicity', 'religion',
       'sexual_orientation', 'year_of_award', 'award', 'movie']
oscars_new_col_order=oscars_short[new_col_order]
oscars_new_col_order.head()

,person,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie
0,Lewis Milestone,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights
1,Frank Lloyd,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady
2,Lewis Milestone,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front
3,Norman Taurog,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy
4,Frank Borzage,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl

# Video 8 Pandas: Selección de Subsets de datos

### Seleccionando subsets de datos
* Seleccinar Series de datos
* Seleccionar filas de Dataframe
* Seleccionar filas de Dataframe y columnas simultaneamente
* Seleccionar datos con ambos integers y etiquetas (?)
* Velocidad en escalar la seleccion
* Cortar filas
* Cortar lexicograficamente

In [347]:
# Hacemos un head para ver los datos que estamos manejando
oscars_short.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",1898-10-03,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [350]:
# Seleccionar con iloc los registros de la fila 5 del dataframe
oscars_short.iloc[5]

birthplace              Glasgow, Scotland
date_of_birth         1886-02-02 00:00:00
race_ethnicity                      White
religion                               Na
sexual_orientation               Straight
year_of_award                        1934
award                       Best Director
movie                           Cavalcade
person                        Frank Lloyd
Name: 5, dtype: object

In [351]:
# Si quisieramos ver un rango hacemos un iloc[0:6] - pero tener en cuenta que la fila 6 no esta incluida porque esta indexada desde 0
oscars_short.iloc[0:6]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd

In [352]:
oscars_short.iloc[5:10]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",1898-10-03,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey

In [355]:
# Muestra tambien el step - aca seleccionamos que muestre de 2 en 2
oscars_short.iloc[5:20:2]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
7,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
9,"Los Angeles, Ca",1898-10-03,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
11,"Pasadena, Ca",1883-02-23,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
13,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
15,"Budapest, Hungary",1886-12-24,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
17,New York City,2018-10-11,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
19,"Mulhouse, Haut-Rhin, Alsace, France",1902-07-01,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler

**iloc vs loc**

In [358]:
# El loc es similar per nos permite hacer un par de cosas mas

In [360]:
# Quiero listar las filas 5 y 10
oscars_short.loc[[5,10]]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
10,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra

### Seleccionar tanto filas como columnas al mismo tiempo

**loc e iloc nos lo permiten hacer**

In [361]:
oscars_short.head()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage

In [364]:
# hacemos un iloc de 1 a 5
oscars_short.iloc[1,5]

1930

In [365]:
# el dato que estamos buscando la posicion 1 en la columna 5

In [367]:
#si quisieramos hacer con dos puntos, hacemos todo hasta esa posicion
# seleccionamos todo desde 0,1 y 2 fila y 0,1,2,3,4 columna
oscars_short.iloc[:3,:5]

          birthplace date_of_birth race_ethnicity religion sexual_orientation
0  Chisinau, Moldova    1895-09-30          White       Na           Straight
1  Glasgow, Scotland    1886-02-02          White       Na           Straight
2  Chisinau, Moldova    1895-09-30          White       Na           Straight

In [369]:
# Si no quisieramos poner las condiciones sobre filas, indicamos ':' pero si enlas columnas tomamos [2,5]
# Es decir todos los datos de la columna 2 y 5
oscars_short.iloc[:,[2,5]]

    race_ethnicity  year_of_award
0            White           1927
1            White           1930
2            White           1931
3            White           1932
4            White           1933
5            White           1934
6            White           1935
7            White           1936
8            White           1937
9            White           1938
10           White           1939
11           White           1940
12           White           1941
13           White           1942
14           White           1943
15           White           1944
16           White           1945
17           White           1962
18           White           1946
19           White           1947
20           White           1948
21           White           1949
22           White           1950
23           White           1951
24           White           1952
25           White           1953
26           White           1954
27           White           1955
28           White           1956
29           White           1957
..             ...            ...
411          Black           2010
412          White           2011
413          Black           2012
414          White           2013
415          Black           2014
416          White           1961
417          White           1941
418          White           1994
419          White           1979
420          White           1942
421          White           2000
422          White           1976
423          White           1946
424          White           1977
425          White           1943
426          White           1958
427          White           1953
428          White           1967
429          White           2005
430          White           2005
431          White           1999
432          White           1969
433          Black           2010
434          White           2001
435          White           1970
436          White           2006
437          White           2009
438          White           1977
439          White           1999
440          White           1949

[441 rows x 2 columns]

In [371]:
# Con loc podemos traer las columnas por su nombre ( a diferencia de iloc)
oscars_short.loc[:,['birthplace','date_of_birth']]

                              birthplace date_of_birth
0                      Chisinau, Moldova    1895-09-30
1                      Glasgow, Scotland    1886-02-02
2                      Chisinau, Moldova    1895-09-30
3                            Chicago, Il    1899-02-23
4                     Salt Lake City, Ut    1894-04-23
5                      Glasgow, Scotland    1886-02-02
6              Bisacquino, Sicily, Italy    1897-05-18
7                     Cape Elizabeth, Me    1894-02-01
8              Bisacquino, Sicily, Italy    1897-05-18
9                        Los Angeles, Ca    1898-10-03
10             Bisacquino, Sicily, Italy    1897-05-18
11                          Pasadena, Ca    1883-02-23
12                    Cape Elizabeth, Me    1894-02-01
13                    Cape Elizabeth, Me    1894-02-01
14   Mulhouse, Haut-Rhin, Alsace, France    1902-07-01
15                     Budapest, Hungary    1886-12-24
16                       Los Angeles, Ca    1898-10-03
17                         New York City    2018-10-11
18               Sucha, Galicia, Austria    2006-06-22
19   Mulhouse, Haut-Rhin, Alsace, France    1902-07-01
20                      Istanbul, Turkey    2009-09-07
21                            Nevada, Mo    2006-08-05
22                      Wilkes-Barre, Pa    2009-02-11
23                      Wilkes-Barre, Pa    2009-02-11
24                           Oakland, Ca    2004-12-18
25                    Cape Elizabeth, Me    1894-02-01
26                       Vienna, Austria    2007-04-29
27                      Istanbul, Turkey    2009-09-07
28                          Lawrence, Ks    2020-01-30
29                           Oakland, Ca    2004-12-18
..                                   ...           ...
411                         Woodlawn, Md    2067-12-11
412                        New York City    2060-09-14
413                       Montgomery, Al    1972-05-25
414                         Brooklyn, Ny    1982-11-12
415                  Mexico City, Mexico    1983-03-01
416              Sucha, Galicia, Austria    2006-06-22
417                     Independence, Mo    2011-07-16
418                          Concord, Ca    2056-07-09
419                        New York City    2039-02-03
420                           Quincy, Il    2006-05-03
421                      Los Angeles, Ca    1975-06-04
422                        New York City    2027-10-31
423                        New York City    1903-06-25
424                           Bascom, Fl    2041-01-14
425                          Walters, Ok    2010-12-13
426                      Thomasville, Ga    2030-02-27
427                           Helena, Mt    1901-05-07
428                      London, England    2032-02-27
429                          Lincoln, Ne    1974-07-30
430                          Lincoln, Ne    1974-07-30
431                      Los Angeles, Ca    1972-09-27
432                           Malden, Ma    2007-06-16
433                         Woodlawn, Md    2067-12-11
434                         La Jolla, Ca    2059-08-14
435               Ilford, Essex, England    2034-12-28
436                      London, England    1971-03-07
437                  Manchester, England    2056-10-20
438                          Chicago, Il    2022-07-26
439                           Laurel, Ne    2028-08-31
440                           Nevada, Mo    2006-08-05

[441 rows x 2 columns]

In [373]:
# las condiciones sobre las filas son : traer desde la fila 1 a la 10 de 2 en 2
# y sobre las columas, la 1
oscars_short.iloc[1:10:2,1]

1   1886-02-02
3   1899-02-23
5   1886-02-02
7   1894-02-01
9   1898-10-03
Name: date_of_birth, dtype: datetime64[ns]

In [374]:
# podemos hacer lo mismo pero con loc
oscars_short.loc[1:10:2,'date_of_birth']

1   1886-02-02
3   1899-02-23
5   1886-02-02
7   1894-02-01
9   1898-10-03
Name: date_of_birth, dtype: datetime64[ns]

### Indexación booleana
Intentaremos encontrar mas de 100 reviews. Para hacer eso, debemos empezar creadno una serie con elementos booleanos para cada uno de los registros involucrados

In [377]:
# Armamos una SERIE
oscars_last_20_years = oscars_short['year_of_award']>1999

In [376]:
oscars_last_20_years

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
411     True
412     True
413     True
414     True
415     True
416    False
417    False
418    False
419    False
420    False
421     True
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429     True
430     True
431    False
432    False
433     True
434     True
435    False
436     True
437     True
438    False
439    False
440    False
Name: year_of_award, Length: 441, dtype: bool

In [378]:
# como hacer para seleccionar datos con indices booleanos
# Vemos que podemos sumar los valores booleanos, agregando 1 si es True y 0 si es False.
# Entonces si queremos saber cuantos de esos registros estan fechados en los ultimos 20 años
# lo unico quedebemos saber es sumar dichos valores
oscars_last_20_years.sum()

82

In [379]:
# yo se que hay 82 oscars entregados durante los ultimos 20 años

In [380]:
# Si quisieramos saber el %, podemos usar mean y multiplicar por 100
oscars_last_20_years.mean()*100

18.594104308390023

In [381]:
oscars_last_20_years.describe()

count       441
unique        2
top       False
freq        359
Name: year_of_award, dtype: object

In [383]:
oscars_last_20_years.value_counts()

False    359
True      82
Name: year_of_award, dtype: int64

In [384]:
# Lo que se hizo entonces fue crear una serie booleana, comparando una columna con una condicion (que sea > 1999).
# Tambien podemos crear series basados en 2 columnas diferentes

In [ ]:
# Ahora vamos a hacer lo mismo pero en lugar de una columna numerica, lo vamos a hacer con una columna con Strings.
# Nos vamos aifjar los premios que contenga "Mejor Director"

In [389]:
# Consulta: no me estan dando los resultados buscando por Mejor Director

In [395]:
oscars_short.columns

Index(['birthplace', 'date_of_birth', 'race_ethnicity', 'religion',
       'sexual_orientation', 'year_of_award', 'award', 'movie', 'person'],
      dtype='object')

In [398]:
oscars_short['award']

0                Best Director
1                Best Director
2                Best Director
3                Best Director
4                Best Director
5                Best Director
6                Best Director
7                Best Director
8                Best Director
9                Best Director
10               Best Director
11               Best Director
12               Best Director
13               Best Director
14               Best Director
15               Best Director
16               Best Director
17               Best Director
18               Best Director
19               Best Director
20               Best Director
21               Best Director
22               Best Director
23               Best Director
24               Best Director
25               Best Director
26               Best Director
27               Best Director
28               Best Director
29               Best Director
                ...
411    Best Supporting Actress
412    Best Supporting Actress
413    Best Supporting Actress
414    Best Supporting Actress
415    Best Supporting Actress
416              Best Director
417               Best Actress
418                 Best Actor
419              Best Director
420    Best Supporting Actress
421    Best Supporting Actress
422    Best Supporting Actress
423    Best Supporting Actress
424               Best Actress
425      Best Supporting Actor
426               Best Actress
427                 Best Actor
428               Best Actress
429               Best Actress
430               Best Actress
431               Best Actress
432      Best Supporting Actor
433    Best Supporting Actress
434    Best Supporting Actress
435               Best Actress
436    Best Supporting Actress
437              Best Director
438      Best Supporting Actor
439      Best Supporting Actor
440              Best Director
Name: award, Length: 441, dtype: object

In [399]:
oscars_best_director = oscars_short.award.str.contains('Best Director')

In [400]:
oscars_best_director.head()

0    True
1    True
2    True
3    True
4    True
Name: award, dtype: bool

In [401]:
oscars_best_director.value_counts()

False    350
True      91
Name: award, dtype: int64

In [402]:
# Estas condiciones las podemos combinar
oscars_last_20_years & oscars_best_director

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437     True
438    False
439    False
440    False
Length: 441, dtype: bool

In [403]:
# con esta combinacion podemos decir que de los ultimos 20 años y mejor director
(oscars_last_20_years & oscars_best_director).value_counts()

False    425
True      16
dtype: int64

## Filtrando con indices booleanos
Podemos usar series booleanas creadas para filtrar informacion de los registros que mapean con ciertas condiciones que necesitamos informar

In [404]:
# si queremos filtar cierta informacion podemos directamente pasar como parametro la serie que acabamos de crear
# registros que tienen True en oscars_last_20_years
# Nos va a devolver los registros que cumples con la condicion de los premios entregados en los ultimos 20 años
# son los 82 registros
oscars_short[oscars_last_20_years]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
41,"St. Louis Park, Mn",2054-11-29,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Joel Coen
73,"Reading, Berkshire, England",2065-08-01,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",2063-01-14,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",2054-03-01,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",2033-08-18,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",2061-10-31,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",2030-05-31,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",2042-11-17,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",2057-09-21,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",2051-11-27,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972-01-01,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",2067-03-29,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
158,"South Orange, Nj",2059-07-26,White,Na,Matter of Dispute,2000,Best Actor,American Beauty,Kevin Spacey
159,"Wellington, New Zealand",2064-04-07,White,Na,Straight,2001,Best Actor,Gladiator,Russell Crowe
160,"Mount Vernon, Ny",2054-12-28,Black,Protestant,Straight,2002,Best Actor,Training Day,Denzel Washington
161,New York City,1973-04-14,White,Jewish,Straight,2003,Best Actor,The Pianist,Adrien Brody
162,"Burbank, Ca",2060-08-17,White,Roman Catholic,Straight,2003,Best Actor,Mystic River,Sean Penn
163,"Terrell, Tx",2067-12-13,Black,Baptist,Straight,2005,Best Actor,Ray,Jamie Foxx
164,"Fairport, Ny",2067-07-23,White,Na,Straight,2006,Best Actor,Capote,Philip Seymour Hoffman
165,"Longview, Tx",2061-07-15,Black,Na,Straight,2007,Best Actor,The Last King of Scotland,Forest Whitaker
166,"London, England",2057-04-29,White,Na,Straight,2008,Best Actor,There Will Be Blood,Daniel Day-Lewis
167,"Burbank, Ca",2060-08-17,White,Roman Catholic,Straight,2009,Best Actor,Milk,Sean Penn
168,"Los Angeles, Ca",2049-12-04,White,Lutheran,Straight,2010,Best Actor,Crazy Heart,Jeff Bridges
169,"Grayshott, Hampshire, England",2060-09-10,White,Na,Straight,2011,Best Actor,The King's Speech,Colin Firth
170,"Rueil-Malmaison, Hauts-De-Seine, France",1972-06-19,White,Na,Straight,2012,Best Actor,The Artist,Jean Dujardin
171,"London, England",2057-04-29,White,Na,Straight,2013,Best Actor,Lincoln,Daniel Day-Lewis
172,"Uvalde, Tx",2069-11-04,White,Na,Straight,2014,Best Actor,Dallas Buyers Club,Matthew McConaughey
...,...,...,...,...,...,...,...,...,...
330,"Chiswick, London, England",2045-07-26,White,Na,Straight,2007,Best Actress,The Queen,Helen Mirren
331,"Paris, France",1975-09-30,White,Na,Straight,2008,Best Actress,The Passionate Life of Edith Piaf,Marion Cotillard
332,"Reading, England",1975-10-05,White,Na,Straight,2009,Best Actress,The Reader,Kate Winslet
333,"Arlington, Va",2064-07-26,White,Na,Straight,2010,Best Actress,The Blind Side,Sandra Bullock
334,"Jerusalem, Israel",1981-06-09,White,Jewish,Straight,2011,Best Actress,Black Swan,Natalie Portman
335,"Summit, Nj",2049-06-22,White,Na,Straight,2012,Best Actress,The Iron Lady,Meryl Streep
336,"Louisville, Ky",1990-08-15,White,Na,Na,2013,Best Actress,Silver Linings Playbook,Jennifer Lawrence
337,"Melbourne, Victoria, Australia",2069-05-14,White,Na,Straight,2014,Best Actress,Blue Jasmine,Cate Blanchett
401,"Los Angeles, Ca",1975-06-04,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
402,"La Jolla, Ca",2059-08-14,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
403,"Catskill Mountains, Ny",1970-12-12,White,Jewish,Straight,2002,Best Supporting Actress,A Beautiful Mind,Jennifer Connelly
404,"Mumbles, Wales",2069-09-25,White,Roman Catholic,Straight,2003,Best Supporting Actress,Chicago,Catherine Zeta-Jones
405,"Katy, Tx",2069-04-25,White,Na,Straight,2004,Best Supporting Actress,Cold Mountain,RenÌ©e Zellweger
406,"Melbourne, Victoria, Australia",2069-05-14,White,Na,Straight,2005,Best Supporting Actress,The Aviator,Cate Blanchett
407,"London, England",1971-03-07,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
408,"Chicago, Il",1981-09-12,Black,Baptist,Straight,2007,Best Supporting Actress,Dreamgirls,Jennifer Hudson
409,"London, England",2060-11-05,White,Na,Straight,2007,Best Supporting Actress,Michael Clayton,Tilda Swinton
410,"Madrid, Spain",1974-04-28,Hispanic,Buddhist,Straight,2009,Best Supporting Actress,Vicky Cristina Barcelona,Penelope Cruz
411,"Woodlawn, Md",2067-12-11,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
412,New York City,2060-09-14,White,Na,Straight,2011,Best Supporting Actress,The Fighter,Melissa Leo
413,"Montgomery, Al",1972-05-25,Black,Na,Na,2012,Best Supporting Actress,The Help,Octavia Spencer
414,"Brooklyn, Ny",1982-11-12,White,Christian,Straight,2013,Best Supporting Actress,Les MisÌ©rables,Anne Hathaway
415,"Mexico City, Mexico",1983-03-01,Black,Na,Na,2014,Best Supporting Actress,12 Years a Slave,Lupita Nyong'o
421,"Los Angeles, Ca",1975-06-04,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
429,"Lincoln, Ne",1974-07-30,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",1974-07-30,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
433,"Woodlawn, Md",2067-12-11,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",2059-08-14,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
436,"London, England",1971-03-07,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle

In [406]:
# Me traigo los registros con los premios a mejor director
oscars_short[oscars_best_director]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
0,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",1895-09-30,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",1899-02-23,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
4,"Salt Lake City, Ut",1894-04-23,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",1886-02-02,White,Na,Straight,1934,Best Director,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1935,Best Director,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1936,Best Director,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1937,Best Director,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",1898-10-03,White,Na,Straight,1938,Best Director,The Awful Truth,Leo McCarey
10,"Bisacquino, Sicily, Italy",1897-05-18,White,Roman Catholic,Straight,1939,Best Director,You Can't Take It with You,Frank Capra
11,"Pasadena, Ca",1883-02-23,White,Na,Straight,1940,Best Director,Gone with the Wind,Victor Fleming
12,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1941,Best Director,The Grapes of Wrath,John Ford
13,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1942,Best Director,How Green Was My Valley,John Ford
14,"Mulhouse, Haut-Rhin, Alsace, France",1902-07-01,White,Na,Straight,1943,Best Director,Mrs. Miniver,William Wyler
15,"Budapest, Hungary",1886-12-24,White,Na,Straight,1944,Best Director,Casablanca,Michael Curtiz
16,"Los Angeles, Ca",1898-10-03,White,Na,Straight,1945,Best Director,Going My Way,Leo McCarey
17,New York City,2018-10-11,White,Jewish,Gay,1962,Best Director,West Side Story,Jerome Robbins
18,"Sucha, Galicia, Austria",2006-06-22,White,Jewish,Straight,1946,Best Director,The Lost Weekend,Billy Wilder
19,"Mulhouse, Haut-Rhin, Alsace, France",1902-07-01,White,Na,Straight,1947,Best Director,The Best Years of Our Lives,William Wyler
20,"Istanbul, Turkey",2009-09-07,White,Na,Straight,1948,Best Director,Gentleman's Agreement,Elia Kazan
21,"Nevada, Mo",2006-08-05,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston
22,"Wilkes-Barre, Pa",2009-02-11,White,Jewish,Straight,1950,Best Director,A Letter to Three Wives,Joseph L. Mankiewicz
23,"Wilkes-Barre, Pa",2009-02-11,White,Jewish,Straight,1951,Best Director,All About Eve,Joseph L. Mankiewicz
24,"Oakland, Ca",2004-12-18,White,Na,Straight,1952,Best Director,A Place in the Sun,George Stevens
25,"Cape Elizabeth, Me",1894-02-01,White,Roman Catholic,Bisexual,1953,Best Director,The Quiet Man,John Ford
26,"Vienna, Austria",2007-04-29,White,Jewish,Straight,1954,Best Director,From Here to Eternity,Fred Zinnemann
27,"Istanbul, Turkey",2009-09-07,White,Na,Straight,1955,Best Director,On the Waterfront,Elia Kazan
28,"Lawrence, Ks",2020-01-30,White,Presbyterian,Straight,1956,Best Director,Marty,Delbert Mann
29,"Oakland, Ca",2004-12-18,White,Na,Straight,1957,Best Director,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...
61,"Parma, Emilia-Romagna, Italy",2041-03-16,White,Na,Straight,1988,Best Director,The Last Emperor,Bernardo Bertolucci
62,"Baltimore, Md",2042-04-06,White,Jewish,Straight,1989,Best Director,Rain Man,Barry Levinson
63,New York City,2046-09-15,White,Atheist,Straight,1990,Best Director,Born on the Fourth of July,Oliver Stone
64,"Lynwood, Ca",2055-01-18,White,Baptist,Straight,1991,Best Director,Dances with Wolves,Kevin Costner
65,"Baldwin, Ny",2044-02-22,White,Na,Straight,1992,Best Director,The Silence of the Lambs,Jonathan Demme
66,"San Francisco, Ca",2030-05-31,White,Na,Straight,1993,Best Director,Unforgiven,Clint Eastwood
67,"Cincinnati, Oh",2046-12-18,White,Jewish,Straight,1994,Best Director,Schindler's List,Steven Spielberg
68,"Chicago, Il",2052-05-14,White,Roman Catholic,Straight,1995,Best Director,Forrest Gump,Robert Zemeckis
69,"Peekskill, Ny",2056-01-03,White,Roman Catholic,Straight,1996,Best Director,Braveheart,Mel Gibson
70,"Ryde, Isle of Wight, England",2054-01-06,White,Na,Straight,1997,Best Director,The English Patient,Anthony Minghella
71,"Kapuskasing, Ontario, Canada",2054-08-16,White,Atheist,Straight,1998,Best Director,Titanic,James Cameron
72,"Cincinnati, Oh",2046-12-18,White,Jewish,Straight,1999,Best Director,Saving Private Ryan,Steven Spielberg
73,"Reading, Berkshire, England",2065-08-01,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",2063-01-14,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",2054-03-01,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",2033-08-18,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",2061-10-31,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",2030-05-31,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",2042-11-17,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",2057-09-21,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",2051-11-27,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972-01-01,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",2067-03-29,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
416,"Sucha, Galicia, Austria",2006-06-22,White,Jewish,Straight,1961,Best Director,The Apartment,Billy Wilder
419,New York City,2039-02-03,White,Na,Straight,1979,Best Director,The Deer Hunter,Michael Cimino
437,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
440,"Nevada, Mo",2006-08-05,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [407]:
# Y si queremos combinar las dos condiciones, tambien se pueden
oscars_short[oscars_last_20_years&oscars_best_director]

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
41,"St. Louis Park, Mn",2054-11-29,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Joel Coen
73,"Reading, Berkshire, England",2065-08-01,White,Na,Straight,2000,Best Director,American Beauty,Sam Mendes
74,"Atlanta, Ga",2063-01-14,White,Atheist,Straight,2001,Best Director,Traffic,Steven Soderbergh
75,"Duncan, Ok",2054-03-01,White,Na,Straight,2002,Best Director,A Beautiful Mind,Ron Howard
76,"Paris, France",2033-08-18,White,See Note,Straight,2003,Best Director,The Pianist,Roman Polanski
77,"Wellington, New Zealand",2061-10-31,White,Na,Straight,2004,Best Director,The Lord of the Rings: Return of the King,Peter Jackson
78,"San Francisco, Ca",2030-05-31,White,Na,Straight,2005,Best Director,Million Dollar Baby,Clint Eastwood
79,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2006,Best Director,Brokeback Mountain,Ang Lee
80,"Flushing, Ny",2042-11-17,White,Roman Catholic,Straight,2007,Best Director,The Departed,Martin Scorsese
81,"St. Louis Park, Mn",2057-09-21,White,Jewish,Straight,2008,Best Director,No Country for Old Men,Ethan Coen
82,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
83,"San Carlos, Ca",2051-11-27,White,Na,Straight,2009,Best Director,The Hurt Locker,Kathryn Bigelow
84,"London, England",1972-01-01,White,Na,Na,2011,Best Director,The King's Speech,Tom Hooper
85,"Paris, France",2067-03-29,White,Jewish,Straight,2012,Best Director,The Artist,Michel Hazanavicius
86,"Pingtung, Taiwan",2054-10-23,Asian,Na,Straight,2013,Best Director,Life of Pi,Ang Lee
437,"Manchester, England",2056-10-20,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle